SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE PROCEDURE [etl].[Load_ods_Eloqua_Contact]
(
	@BatchId INT = 0,
	@Options NVARCHAR(MAX) = NULL
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     svcETL
Date:     01/23/2016
Comments: Initial creation
*************************************************************************************/

DECLARE @RunTime DATETIME = GETDATE()

DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName NVARCHAR(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM src.Eloqua_Contact),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0'

BEGIN TRY 

PRINT 'Execution Id: ' + CONVERT(NVARCHAR(100),@ExecutionId)

SELECT CAST(NULL AS BINARY(32)) ETL_DeltaHashKey, ETL_UpdatedDate, ETL_IsDeleted, ETL_DeletedDate, ID, Name, AccountName, BouncebackDate, IsBounceback, IsSubscribed, PostalCode, Province, SubscriptionDate, UnsubscriptionDate, CreatedAt, CreatedBy, AccessedAt, CurrentStatus, Depth, UpdatedAt, UpdatedBy, EmailAddress, FirstName, LastName, Company, Address1, Address2, Address3, City, Country, MobilePhone, BusinessPhone, Fax, Title, SalesPerson, C_EmailDisplayName, C_State_Prov, C_Zip_Postal, C_Salutation, C_Owner, C_IDNumber, C_Account, C_SFDCContactID, C_SFDCLeadID, C_Website, C_DateCreated, C_DateModified, C_SalesnetAccountID, C_OptIn, C_PermissionSource, C_PermissionMedium, C_PermissionDate, ContactIDExt, C_SFDCAccountID, C_LastModifiedByExtIntegrateSystem, C_SFDCLastCampaignID, C_SFDCLastCampaignStatus, C_SFDCLastCampaignName, C_Last_Lead_Rating1, C_Last_Lead_Score1, C_Lead_Score___Historical_All_Time1, C_Lead_Rating___Historical_All_Time__HAT_1, C_Company_Revenue1, C_Buying_Horizon1, C_SFDC_EmailOptOut1, C_MSCRMContactID, C_MSCRMLeadID, C_SiebelOnDemandContactID, C_SiebelOnDemandLeadID, C_SalesLogixContactID, C_Lead_Source___Most_Recent1, C_Lead_Source___Original1, C_Industry1, C_Annual_Revenue1, C_Lead_Status1, C_SFDC_Lead_Rating1, C_SiebelOnDemandAccountID, C_SalesLogixAccountID, C_MSCRMAccountID, C_Job_Role1, C_Last_Website_Visit_Date_and_Time1, C_LS___High_Value_Website_Content1, C_NetSuiteContactID, C_NetSuiteLeadID, C_NetSuiteCompanyID, C_DUNS_Number, C_Doing_Business_As, C_CEO_Name, C_Industry, C_SIC_Code, C_Established_In, C_Annual_Sales_Indicator, C_Annual_Sales, C_Total_Employees, C_Total_Employees_Indicator, C_StrikeIron_Country, C_Business_Structure, C_Lead_Score_Date___Most_Recent1, C_Birth_Date1, C_Number_Of_Tickets1, C_Interest___Kings1, C_Interest___Monarchs1, C_Interest___Other_Sporting_Events1, C_Interest___Family_Shows1, C_Interest___Concerts1, C_Archtics_Account_ID1, C_Account_Type_Description1, C_add_date1, C_upd_datetime1, C_Middle_Name1, C_Evening_Phone1, C_Customer_Status1, C_Day_Phone1, C_Product_Interest___Kings_Full_Season1, C_Product_Interest___Kings_Partial_Season1, C_Product_Interest___Kings_Group_Tickets1, C_Product_Interest_Kings_Row_Tickets1, C_Product_Interest___Kings_Suites1, C_Temporary_Segment1, C_Sub___MSE_News1, C_Sub___MSE_Offers1, C_Sub___AR_Com1, C_Rep___Ticket_Services1, C_Rep___Ticket_Services__email_1, C_Rep___Ticket_Services__phone_1, C_Rep___Group_Sales11, C_Product_Interest___Kings_Individual1, C_Lead_Scoring_Date1, C_Zip_Code_Ty_e1, C_Rep___Season_Sales11, C_Rep___Premium_Sales1, C_Interest___Business11, C_LN___Timestamp11, C_Premium_Product_Type1, C_Birthday___This_Year13, C__08Acq_More_Info11, C__501_c__3__Fed_Tax_ID1, C_Birthday___This_Year_PW1, C_COPPA___Under_13_1, C_How_to_Use_Tickets1, C_Premium_Suite_Letter1, C_TSSC_Temp_Field_1__MVP_Relo_Time_1, C_ETW_Source1, C_Rep___Partner_Business_Manager1, C_TSSC_Temp_Field_33__STH_Commuinty_BBQ_Seg_1, C_Lead_Rating___Monarchs1, C_KG_Payment_Date1, C_KG_Payment_Amount1, C_KG_Payment_Card1, C_KG_Payment_Multi_Card1, C_Sharepartner_Flag1, C_Sharepartner_Account_ID1, C_Sharepartner_Team1, C_Are_You_a_Total_Access_Member1, C_TSSC_Temp_Field_54__09_Rod_Buyers_1, C_EmailAddressDomain, C_FirstAndLastName, C_Favorite_Player__c_1, C_Birth_Month1, C_SFDC_last_7_day_activity_flag1, C_SFDC_Last_Activity_Date1, C_Engagement_Status1, C_TSSC_Temp_Field_45__Relo_Select_a_Seat_time, C_TSSC_Temp_Field_15__STH_Type_1, C_TSSC_Temp_Field_04__GIN_1, C_TSSC_Temp_Field_05__Open_House_Time_1, C_TSSC_Temp_Field_09__ROTK_OPH_Time_1, C_TSSC_Temp_Field_10__STH_Referral_Rep_1, C_TSSC_Tem_Field_16__STH_Fan_Forums_1, C_TSSC_Temp_Field_18__KBA_Rep_Vip_Invite_1, C_Favorite_Match_Up_11, C_Favorite_Match_Up_21, C_Territory, C_TSSC_Temp_Feild_16__CCK_PURL_Id_1, C_TSSC_Temp_Field_2__KOL_Ticket_Link_1, C_Lead_Source_Most_Recent, C_Lead_Source_Original, C_TSSC_Temp_Field__13KG_Renewal_Rep_1, C_TSSC_Temp_Field_53__Segment_1, C_Placeholder__FirstName_1, C_Placeholder__LastName_1, C_Opt_In_Source1, C_Lead_Score, C_ElqPURLName, C_TSSC_Temp_Field__Rookie_Mini_Camp_1, C_TSSC_Temp_Field_18__Temp_REP_Phone_1, C_TSSC_Temp_Field_24__PD_Time_1, C_TSSC_Temp_Field_25__PD_address_1, C_SFDC_Kings_com_Activity_Flag1, C_SFDC_ESC_com_Activity_Flag1, C_MD5HashedEmailAddress, C_SHA256HashedEmailAddress, C_MD5HashedBusPhone, C_SHA256HashedBusPhone, C_MD5HashedMobilePhone, C_SHA256HashedMobilePhone, C_SFDC_Email_Activity_Flag___Last_30_Days1
INTO #SrcData
FROM src.Eloqua_Contact;

UPDATE #SrcData
SET ETL_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(CONVERT(varchar(25),AccessedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(AccountName),'DBNULL_TEXT') + ISNULL(RTRIM(Address1),'DBNULL_TEXT') + ISNULL(RTRIM(Address2),'DBNULL_TEXT') + ISNULL(RTRIM(Address3),'DBNULL_TEXT') + ISNULL(RTRIM(BouncebackDate),'DBNULL_TEXT') + ISNULL(RTRIM(BusinessPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C__08Acq_More_Info11),'DBNULL_TEXT') + ISNULL(RTRIM(C__501_c__3__Fed_Tax_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Account),'DBNULL_TEXT') + ISNULL(RTRIM(C_Account_Type_Description1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_add_date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Annual_Revenue1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Annual_Sales)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Annual_Sales_Indicator),'DBNULL_TEXT') + ISNULL(RTRIM(C_Archtics_Account_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Are_You_a_Total_Access_Member1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Birth_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(25),C_Birth_Month1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Birthday___This_Year_PW1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Birthday___This_Year13,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Business_Structure),'DBNULL_TEXT') + ISNULL(RTRIM(C_Buying_Horizon1),'DBNULL_TEXT') + ISNULL(RTRIM(C_CEO_Name),'DBNULL_TEXT') + ISNULL(RTRIM(C_Company_Revenue1),'DBNULL_TEXT') + ISNULL(RTRIM(C_COPPA___Under_13_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Customer_Status1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_DateCreated,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_DateModified,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Day_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Doing_Business_As),'DBNULL_TEXT') + ISNULL(RTRIM(C_DUNS_Number),'DBNULL_TEXT') + ISNULL(RTRIM(C_ElqPURLName),'DBNULL_TEXT') + ISNULL(RTRIM(C_EmailAddressDomain),'DBNULL_TEXT') + ISNULL(RTRIM(C_EmailDisplayName),'DBNULL_TEXT') + ISNULL(RTRIM(C_Engagement_Status1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Established_In),'DBNULL_TEXT') + ISNULL(RTRIM(C_ETW_Source1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Evening_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Favorite_Match_Up_11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Favorite_Match_Up_21),'DBNULL_TEXT') + ISNULL(RTRIM(C_Favorite_Player__c_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_FirstAndLastName),'DBNULL_TEXT') + ISNULL(RTRIM(C_How_to_Use_Tickets1),'DBNULL_TEXT') + ISNULL(RTRIM(C_IDNumber),'DBNULL_TEXT') + ISNULL(RTRIM(C_Industry),'DBNULL_TEXT') + ISNULL(RTRIM(C_Industry1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interest___Business11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interest___Concerts1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interest___Family_Shows1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interest___Kings1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interest___Monarchs1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Interest___Other_Sporting_Events1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Job_Role1),'DBNULL_TEXT') + ISNULL(RTRIM(C_KG_Payment_Amount1),'DBNULL_TEXT') + ISNULL(RTRIM(C_KG_Payment_Card1),'DBNULL_TEXT') + ISNULL(RTRIM(C_KG_Payment_Date1),'DBNULL_TEXT') + ISNULL(RTRIM(C_KG_Payment_Multi_Card1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Last_Lead_Rating1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Last_Lead_Score1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),C_Last_Website_Visit_Date_and_Time1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_LastModifiedByExtIntegrateSystem,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Lead_Rating___Historical_All_Time__HAT_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Rating___Monarchs1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Score),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Lead_Score___Historical_All_Time1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Score_Date___Most_Recent1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Scoring_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Lead_Source___Most_Recent1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Source___Original1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Source_Most_Recent),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Source_Original),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Status1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_LN___Timestamp11,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(25),C_LS___High_Value_Website_Content1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_MD5HashedBusPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedEmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedMobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_Middle_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(C_NetSuiteCompanyID),'DBNULL_TEXT') + ISNULL(RTRIM(C_NetSuiteContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_NetSuiteLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Number_Of_Tickets1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Opt_In_Source1),'DBNULL_TEXT') + ISNULL(RTRIM(C_OptIn),'DBNULL_TEXT') + ISNULL(RTRIM(C_Owner),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_PermissionDate,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_PermissionMedium),'DBNULL_TEXT') + ISNULL(RTRIM(C_PermissionSource),'DBNULL_TEXT') + ISNULL(RTRIM(C_Placeholder__FirstName_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Placeholder__LastName_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Premium_Product_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Premium_Suite_Letter1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Interest___Kings_Full_Season1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Interest___Kings_Group_Tickets1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Interest___Kings_Individual1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Interest___Kings_Partial_Season1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Interest___Kings_Suites1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Interest_Kings_Row_Tickets1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Group_Sales11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Partner_Business_Manager1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Premium_Sales1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Season_Sales11),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Ticket_Services__email_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Ticket_Services__phone_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rep___Ticket_Services1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SalesLogixAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SalesLogixContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SalesnetAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_Salutation),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Email_Activity_Flag___Last_30_Days1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_EmailOptOut1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_ESC_com_Activity_Flag1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_Kings_com_Activity_Flag1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_last_7_day_activity_flag1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_SFDC_Last_Activity_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_SFDC_Lead_Rating1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignName),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignStatus),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedBusPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedEmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedMobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sharepartner_Account_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sharepartner_Flag1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sharepartner_Team1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SIC_Code),'DBNULL_TEXT') + ISNULL(RTRIM(C_SiebelOnDemandAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SiebelOnDemandContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SiebelOnDemandLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(C_State_Prov),'DBNULL_TEXT') + ISNULL(RTRIM(C_StrikeIron_Country),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sub___AR_Com1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sub___MSE_News1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Sub___MSE_Offers1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Temporary_Segment1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Territory),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Total_Employees)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Total_Employees_Indicator),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Tem_Field_16__STH_Fan_Forums_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Feild_16__CCK_PURL_Id_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field__13KG_Renewal_Rep_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field__Rookie_Mini_Camp_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_04__GIN_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_05__Open_House_Time_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_09__ROTK_OPH_Time_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_1__MVP_Relo_Time_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_10__STH_Referral_Rep_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_15__STH_Type_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_18__KBA_Rep_Vip_Invite_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_18__Temp_REP_Phone_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_2__KOL_Ticket_Link_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_24__PD_Time_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_25__PD_address_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_33__STH_Commuinty_BBQ_Seg_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_45__Relo_Select_a_Seat_time),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_53__Segment_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TSSC_Temp_Field_54__09_Rod_Buyers_1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_upd_datetime1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Website),'DBNULL_TEXT') + ISNULL(RTRIM(C_Zip_Code_Ty_e1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Zip_Postal),'DBNULL_TEXT') + ISNULL(RTRIM(City),'DBNULL_TEXT') + ISNULL(RTRIM(Company),'DBNULL_TEXT') + ISNULL(RTRIM(ContactIDExt),'DBNULL_TEXT') + ISNULL(RTRIM(Country),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),CreatedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(CreatedBy),'DBNULL_TEXT') + ISNULL(RTRIM(CurrentStatus),'DBNULL_TEXT') + ISNULL(RTRIM(Depth),'DBNULL_TEXT') + ISNULL(RTRIM(EmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(Fax),'DBNULL_TEXT') + ISNULL(RTRIM(FirstName),'DBNULL_TEXT') + ISNULL(RTRIM(ID),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),IsBounceback)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),IsSubscribed)),'DBNULL_BIT') + ISNULL(RTRIM(LastName),'DBNULL_TEXT') + ISNULL(RTRIM(MobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(Name),'DBNULL_TEXT') + ISNULL(RTRIM(PostalCode),'DBNULL_TEXT') + ISNULL(RTRIM(Province),'DBNULL_TEXT') + ISNULL(RTRIM(SalesPerson),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),SubscriptionDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(Title),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),UnsubscriptionDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(25),UpdatedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(UpdatedBy),'DBNULL_TEXT'))


CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (ID);
CREATE NONCLUSTERED INDEX IDX_ETL_DeltaHashKey ON #SrcData (ETL_DeltaHashKey);


MERGE ods.Eloqua_Contact AS myTarget
USING #SrcData AS mySource
ON myTarget.ID = mySource.ID

WHEN MATCHED AND (
     ISNULL(mySource.ETL_DeltaHashKey,-1) <> ISNULL(myTarget.ETL_DeltaHashKey, -1)
	 OR myTarget.ETL_IsDeleted = 1
)
THEN UPDATE SET
      myTarget.[ETL_UpdatedDate] = @RunTime
	 ,myTarget.[ETL_IsDeleted] = 0
	 ,myTarget.[ETL_DeletedDate] = NULL
     ,myTarget.[ETL_DeltaHashKey] = mySource.[ETL_DeltaHashKey]
     ,myTarget.[ID] = mySource.[ID]
     ,myTarget.[Name] = mySource.[Name]
     ,myTarget.[AccountName] = mySource.[AccountName]
     ,myTarget.[BouncebackDate] = mySource.[BouncebackDate]
     ,myTarget.[IsBounceback] = mySource.[IsBounceback]
     ,myTarget.[IsSubscribed] = mySource.[IsSubscribed]
     ,myTarget.[PostalCode] = mySource.[PostalCode]
     ,myTarget.[Province] = mySource.[Province]
     ,myTarget.[SubscriptionDate] = mySource.[SubscriptionDate]
     ,myTarget.[UnsubscriptionDate] = mySource.[UnsubscriptionDate]
     ,myTarget.[CreatedAt] = mySource.[CreatedAt]
     ,myTarget.[CreatedBy] = mySource.[CreatedBy]
     ,myTarget.[AccessedAt] = mySource.[AccessedAt]
     ,myTarget.[CurrentStatus] = mySource.[CurrentStatus]
     ,myTarget.[Depth] = mySource.[Depth]
     ,myTarget.[UpdatedAt] = mySource.[UpdatedAt]
     ,myTarget.[UpdatedBy] = mySource.[UpdatedBy]
     ,myTarget.[EmailAddress] = mySource.[EmailAddress]
     ,myTarget.[FirstName] = mySource.[FirstName]
     ,myTarget.[LastName] = mySource.[LastName]
     ,myTarget.[Company] = mySource.[Company]
     ,myTarget.[Address1] = mySource.[Address1]
     ,myTarget.[Address2] = mySource.[Address2]
     ,myTarget.[Address3] = mySource.[Address3]
     ,myTarget.[City] = mySource.[City]
     ,myTarget.[Country] = mySource.[Country]
     ,myTarget.[MobilePhone] = mySource.[MobilePhone]
     ,myTarget.[BusinessPhone] = mySource.[BusinessPhone]
     ,myTarget.[Fax] = mySource.[Fax]
     ,myTarget.[Title] = mySource.[Title]
     ,myTarget.[SalesPerson] = mySource.[SalesPerson]
     ,myTarget.[C_EmailDisplayName] = mySource.[C_EmailDisplayName]
     ,myTarget.[C_State_Prov] = mySource.[C_State_Prov]
     ,myTarget.[C_Zip_Postal] = mySource.[C_Zip_Postal]
     ,myTarget.[C_Salutation] = mySource.[C_Salutation]
     ,myTarget.[C_Owner] = mySource.[C_Owner]
     ,myTarget.[C_IDNumber] = mySource.[C_IDNumber]
     ,myTarget.[C_Account] = mySource.[C_Account]
     ,myTarget.[C_SFDCContactID] = mySource.[C_SFDCContactID]
     ,myTarget.[C_SFDCLeadID] = mySource.[C_SFDCLeadID]
     ,myTarget.[C_Website] = mySource.[C_Website]
     ,myTarget.[C_DateCreated] = mySource.[C_DateCreated]
     ,myTarget.[C_DateModified] = mySource.[C_DateModified]
     ,myTarget.[C_SalesnetAccountID] = mySource.[C_SalesnetAccountID]
     ,myTarget.[C_OptIn] = mySource.[C_OptIn]
     ,myTarget.[C_PermissionSource] = mySource.[C_PermissionSource]
     ,myTarget.[C_PermissionMedium] = mySource.[C_PermissionMedium]
     ,myTarget.[C_PermissionDate] = mySource.[C_PermissionDate]
     ,myTarget.[ContactIDExt] = mySource.[ContactIDExt]
     ,myTarget.[C_SFDCAccountID] = mySource.[C_SFDCAccountID]
     ,myTarget.[C_LastModifiedByExtIntegrateSystem] = mySource.[C_LastModifiedByExtIntegrateSystem]
     ,myTarget.[C_SFDCLastCampaignID] = mySource.[C_SFDCLastCampaignID]
     ,myTarget.[C_SFDCLastCampaignStatus] = mySource.[C_SFDCLastCampaignStatus]
     ,myTarget.[C_SFDCLastCampaignName] = mySource.[C_SFDCLastCampaignName]
     ,myTarget.[C_Last_Lead_Rating1] = mySource.[C_Last_Lead_Rating1]
     ,myTarget.[C_Last_Lead_Score1] = mySource.[C_Last_Lead_Score1]
     ,myTarget.[C_Lead_Score___Historical_All_Time1] = mySource.[C_Lead_Score___Historical_All_Time1]
     ,myTarget.[C_Lead_Rating___Historical_All_Time__HAT_1] = mySource.[C_Lead_Rating___Historical_All_Time__HAT_1]
     ,myTarget.[C_Company_Revenue1] = mySource.[C_Company_Revenue1]
     ,myTarget.[C_Buying_Horizon1] = mySource.[C_Buying_Horizon1]
     ,myTarget.[C_SFDC_EmailOptOut1] = mySource.[C_SFDC_EmailOptOut1]
     ,myTarget.[C_MSCRMContactID] = mySource.[C_MSCRMContactID]
     ,myTarget.[C_MSCRMLeadID] = mySource.[C_MSCRMLeadID]
     ,myTarget.[C_SiebelOnDemandContactID] = mySource.[C_SiebelOnDemandContactID]
     ,myTarget.[C_SiebelOnDemandLeadID] = mySource.[C_SiebelOnDemandLeadID]
     ,myTarget.[C_SalesLogixContactID] = mySource.[C_SalesLogixContactID]
     ,myTarget.[C_Lead_Source___Most_Recent1] = mySource.[C_Lead_Source___Most_Recent1]
     ,myTarget.[C_Lead_Source___Original1] = mySource.[C_Lead_Source___Original1]
     ,myTarget.[C_Industry1] = mySource.[C_Industry1]
     ,myTarget.[C_Annual_Revenue1] = mySource.[C_Annual_Revenue1]
     ,myTarget.[C_Lead_Status1] = mySource.[C_Lead_Status1]
     ,myTarget.[C_SFDC_Lead_Rating1] = mySource.[C_SFDC_Lead_Rating1]
     ,myTarget.[C_SiebelOnDemandAccountID] = mySource.[C_SiebelOnDemandAccountID]
     ,myTarget.[C_SalesLogixAccountID] = mySource.[C_SalesLogixAccountID]
     ,myTarget.[C_MSCRMAccountID] = mySource.[C_MSCRMAccountID]
     ,myTarget.[C_Job_Role1] = mySource.[C_Job_Role1]
     ,myTarget.[C_Last_Website_Visit_Date_and_Time1] = mySource.[C_Last_Website_Visit_Date_and_Time1]
     ,myTarget.[C_LS___High_Value_Website_Content1] = mySource.[C_LS___High_Value_Website_Content1]
     ,myTarget.[C_NetSuiteContactID] = mySource.[C_NetSuiteContactID]
     ,myTarget.[C_NetSuiteLeadID] = mySource.[C_NetSuiteLeadID]
     ,myTarget.[C_NetSuiteCompanyID] = mySource.[C_NetSuiteCompanyID]
     ,myTarget.[C_DUNS_Number] = mySource.[C_DUNS_Number]
     ,myTarget.[C_Doing_Business_As] = mySource.[C_Doing_Business_As]
     ,myTarget.[C_CEO_Name] = mySource.[C_CEO_Name]
     ,myTarget.[C_Industry] = mySource.[C_Industry]
     ,myTarget.[C_SIC_Code] = mySource.[C_SIC_Code]
     ,myTarget.[C_Established_In] = mySource.[C_Established_In]
     ,myTarget.[C_Annual_Sales_Indicator] = mySource.[C_Annual_Sales_Indicator]
     ,myTarget.[C_Annual_Sales] = mySource.[C_Annual_Sales]
     ,myTarget.[C_Total_Employees] = mySource.[C_Total_Employees]
     ,myTarget.[C_Total_Employees_Indicator] = mySource.[C_Total_Employees_Indicator]
     ,myTarget.[C_StrikeIron_Country] = mySource.[C_StrikeIron_Country]
     ,myTarget.[C_Business_Structure] = mySource.[C_Business_Structure]
     ,myTarget.[C_Lead_Score_Date___Most_Recent1] = mySource.[C_Lead_Score_Date___Most_Recent1]
     ,myTarget.[C_Birth_Date1] = mySource.[C_Birth_Date1]
     ,myTarget.[C_Number_Of_Tickets1] = mySource.[C_Number_Of_Tickets1]
     ,myTarget.[C_Interest___Kings1] = mySource.[C_Interest___Kings1]
     ,myTarget.[C_Interest___Monarchs1] = mySource.[C_Interest___Monarchs1]
     ,myTarget.[C_Interest___Other_Sporting_Events1] = mySource.[C_Interest___Other_Sporting_Events1]
     ,myTarget.[C_Interest___Family_Shows1] = mySource.[C_Interest___Family_Shows1]
     ,myTarget.[C_Interest___Concerts1] = mySource.[C_Interest___Concerts1]
     ,myTarget.[C_Archtics_Account_ID1] = mySource.[C_Archtics_Account_ID1]
     ,myTarget.[C_Account_Type_Description1] = mySource.[C_Account_Type_Description1]
     ,myTarget.[C_add_date1] = mySource.[C_add_date1]
     ,myTarget.[C_upd_datetime1] = mySource.[C_upd_datetime1]
     ,myTarget.[C_Middle_Name1] = mySource.[C_Middle_Name1]
     ,myTarget.[C_Evening_Phone1] = mySource.[C_Evening_Phone1]
     ,myTarget.[C_Customer_Status1] = mySource.[C_Customer_Status1]
     ,myTarget.[C_Day_Phone1] = mySource.[C_Day_Phone1]
     ,myTarget.[C_Product_Interest___Kings_Full_Season1] = mySource.[C_Product_Interest___Kings_Full_Season1]
     ,myTarget.[C_Product_Interest___Kings_Partial_Season1] = mySource.[C_Product_Interest___Kings_Partial_Season1]
     ,myTarget.[C_Product_Interest___Kings_Group_Tickets1] = mySource.[C_Product_Interest___Kings_Group_Tickets1]
     ,myTarget.[C_Product_Interest_Kings_Row_Tickets1] = mySource.[C_Product_Interest_Kings_Row_Tickets1]
     ,myTarget.[C_Product_Interest___Kings_Suites1] = mySource.[C_Product_Interest___Kings_Suites1]
     ,myTarget.[C_Temporary_Segment1] = mySource.[C_Temporary_Segment1]
     ,myTarget.[C_Sub___MSE_News1] = mySource.[C_Sub___MSE_News1]
     ,myTarget.[C_Sub___MSE_Offers1] = mySource.[C_Sub___MSE_Offers1]
     ,myTarget.[C_Sub___AR_Com1] = mySource.[C_Sub___AR_Com1]
     ,myTarget.[C_Rep___Ticket_Services1] = mySource.[C_Rep___Ticket_Services1]
     ,myTarget.[C_Rep___Ticket_Services__email_1] = mySource.[C_Rep___Ticket_Services__email_1]
     ,myTarget.[C_Rep___Ticket_Services__phone_1] = mySource.[C_Rep___Ticket_Services__phone_1]
     ,myTarget.[C_Rep___Group_Sales11] = mySource.[C_Rep___Group_Sales11]
     ,myTarget.[C_Product_Interest___Kings_Individual1] = mySource.[C_Product_Interest___Kings_Individual1]
     ,myTarget.[C_Lead_Scoring_Date1] = mySource.[C_Lead_Scoring_Date1]
     ,myTarget.[C_Zip_Code_Ty_e1] = mySource.[C_Zip_Code_Ty_e1]
     ,myTarget.[C_Rep___Season_Sales11] = mySource.[C_Rep___Season_Sales11]
     ,myTarget.[C_Rep___Premium_Sales1] = mySource.[C_Rep___Premium_Sales1]
     ,myTarget.[C_Interest___Business11] = mySource.[C_Interest___Business11]
     ,myTarget.[C_LN___Timestamp11] = mySource.[C_LN___Timestamp11]
     ,myTarget.[C_Premium_Product_Type1] = mySource.[C_Premium_Product_Type1]
     ,myTarget.[C_Birthday___This_Year13] = mySource.[C_Birthday___This_Year13]
     ,myTarget.[C__08Acq_More_Info11] = mySource.[C__08Acq_More_Info11]
     ,myTarget.[C__501_c__3__Fed_Tax_ID1] = mySource.[C__501_c__3__Fed_Tax_ID1]
     ,myTarget.[C_Birthday___This_Year_PW1] = mySource.[C_Birthday___This_Year_PW1]
     ,myTarget.[C_COPPA___Under_13_1] = mySource.[C_COPPA___Under_13_1]
     ,myTarget.[C_How_to_Use_Tickets1] = mySource.[C_How_to_Use_Tickets1]
     ,myTarget.[C_Premium_Suite_Letter1] = mySource.[C_Premium_Suite_Letter1]
     ,myTarget.[C_TSSC_Temp_Field_1__MVP_Relo_Time_1] = mySource.[C_TSSC_Temp_Field_1__MVP_Relo_Time_1]
     ,myTarget.[C_ETW_Source1] = mySource.[C_ETW_Source1]
     ,myTarget.[C_Rep___Partner_Business_Manager1] = mySource.[C_Rep___Partner_Business_Manager1]
     ,myTarget.[C_TSSC_Temp_Field_33__STH_Commuinty_BBQ_Seg_1] = mySource.[C_TSSC_Temp_Field_33__STH_Commuinty_BBQ_Seg_1]
     ,myTarget.[C_Lead_Rating___Monarchs1] = mySource.[C_Lead_Rating___Monarchs1]
     ,myTarget.[C_KG_Payment_Date1] = mySource.[C_KG_Payment_Date1]
     ,myTarget.[C_KG_Payment_Amount1] = mySource.[C_KG_Payment_Amount1]
     ,myTarget.[C_KG_Payment_Card1] = mySource.[C_KG_Payment_Card1]
     ,myTarget.[C_KG_Payment_Multi_Card1] = mySource.[C_KG_Payment_Multi_Card1]
     ,myTarget.[C_Sharepartner_Flag1] = mySource.[C_Sharepartner_Flag1]
     ,myTarget.[C_Sharepartner_Account_ID1] = mySource.[C_Sharepartner_Account_ID1]
     ,myTarget.[C_Sharepartner_Team1] = mySource.[C_Sharepartner_Team1]
     ,myTarget.[C_Are_You_a_Total_Access_Member1] = mySource.[C_Are_You_a_Total_Access_Member1]
     ,myTarget.[C_TSSC_Temp_Field_54__09_Rod_Buyers_1] = mySource.[C_TSSC_Temp_Field_54__09_Rod_Buyers_1]
     ,myTarget.[C_EmailAddressDomain] = mySource.[C_EmailAddressDomain]
     ,myTarget.[C_FirstAndLastName] = mySource.[C_FirstAndLastName]
     ,myTarget.[C_Favorite_Player__c_1] = mySource.[C_Favorite_Player__c_1]
     ,myTarget.[C_Birth_Month1] = mySource.[C_Birth_Month1]
     ,myTarget.[C_SFDC_last_7_day_activity_flag1] = mySource.[C_SFDC_last_7_day_activity_flag1]
     ,myTarget.[C_SFDC_Last_Activity_Date1] = mySource.[C_SFDC_Last_Activity_Date1]
     ,myTarget.[C_Engagement_Status1] = mySource.[C_Engagement_Status1]
     ,myTarget.[C_TSSC_Temp_Field_45__Relo_Select_a_Seat_time] = mySource.[C_TSSC_Temp_Field_45__Relo_Select_a_Seat_time]
     ,myTarget.[C_TSSC_Temp_Field_15__STH_Type_1] = mySource.[C_TSSC_Temp_Field_15__STH_Type_1]
     ,myTarget.[C_TSSC_Temp_Field_04__GIN_1] = mySource.[C_TSSC_Temp_Field_04__GIN_1]
     ,myTarget.[C_TSSC_Temp_Field_05__Open_House_Time_1] = mySource.[C_TSSC_Temp_Field_05__Open_House_Time_1]
     ,myTarget.[C_TSSC_Temp_Field_09__ROTK_OPH_Time_1] = mySource.[C_TSSC_Temp_Field_09__ROTK_OPH_Time_1]
     ,myTarget.[C_TSSC_Temp_Field_10__STH_Referral_Rep_1] = mySource.[C_TSSC_Temp_Field_10__STH_Referral_Rep_1]
     ,myTarget.[C_TSSC_Tem_Field_16__STH_Fan_Forums_1] = mySource.[C_TSSC_Tem_Field_16__STH_Fan_Forums_1]
     ,myTarget.[C_TSSC_Temp_Field_18__KBA_Rep_Vip_Invite_1] = mySource.[C_TSSC_Temp_Field_18__KBA_Rep_Vip_Invite_1]
     ,myTarget.[C_Favorite_Match_Up_11] = mySource.[C_Favorite_Match_Up_11]
     ,myTarget.[C_Favorite_Match_Up_21] = mySource.[C_Favorite_Match_Up_21]
     ,myTarget.[C_Territory] = mySource.[C_Territory]
     ,myTarget.[C_TSSC_Temp_Feild_16__CCK_PURL_Id_1] = mySource.[C_TSSC_Temp_Feild_16__CCK_PURL_Id_1]
     ,myTarget.[C_TSSC_Temp_Field_2__KOL_Ticket_Link_1] = mySource.[C_TSSC_Temp_Field_2__KOL_Ticket_Link_1]
     ,myTarget.[C_Lead_Source_Most_Recent] = mySource.[C_Lead_Source_Most_Recent]
     ,myTarget.[C_Lead_Source_Original] = mySource.[C_Lead_Source_Original]
     ,myTarget.[C_TSSC_Temp_Field__13KG_Renewal_Rep_1] = mySource.[C_TSSC_Temp_Field__13KG_Renewal_Rep_1]
     ,myTarget.[C_TSSC_Temp_Field_53__Segment_1] = mySource.[C_TSSC_Temp_Field_53__Segment_1]
     ,myTarget.[C_Placeholder__FirstName_1] = mySource.[C_Placeholder__FirstName_1]
     ,myTarget.[C_Placeholder__LastName_1] = mySource.[C_Placeholder__LastName_1]
     ,myTarget.[C_Opt_In_Source1] = mySource.[C_Opt_In_Source1]
     ,myTarget.[C_Lead_Score] = mySource.[C_Lead_Score]
     ,myTarget.[C_ElqPURLName] = mySource.[C_ElqPURLName]
     ,myTarget.[C_TSSC_Temp_Field__Rookie_Mini_Camp_1] = mySource.[C_TSSC_Temp_Field__Rookie_Mini_Camp_1]
     ,myTarget.[C_TSSC_Temp_Field_18__Temp_REP_Phone_1] = mySource.[C_TSSC_Temp_Field_18__Temp_REP_Phone_1]
     ,myTarget.[C_TSSC_Temp_Field_24__PD_Time_1] = mySource.[C_TSSC_Temp_Field_24__PD_Time_1]
     ,myTarget.[C_TSSC_Temp_Field_25__PD_address_1] = mySource.[C_TSSC_Temp_Field_25__PD_address_1]
     ,myTarget.[C_SFDC_Kings_com_Activity_Flag1] = mySource.[C_SFDC_Kings_com_Activity_Flag1]
     ,myTarget.[C_SFDC_ESC_com_Activity_Flag1] = mySource.[C_SFDC_ESC_com_Activity_Flag1]
     ,myTarget.[C_MD5HashedEmailAddress] = mySource.[C_MD5HashedEmailAddress]
     ,myTarget.[C_SHA256HashedEmailAddress] = mySource.[C_SHA256HashedEmailAddress]
     ,myTarget.[C_MD5HashedBusPhone] = mySource.[C_MD5HashedBusPhone]
     ,myTarget.[C_SHA256HashedBusPhone] = mySource.[C_SHA256HashedBusPhone]
     ,myTarget.[C_MD5HashedMobilePhone] = mySource.[C_MD5HashedMobilePhone]
     ,myTarget.[C_SHA256HashedMobilePhone] = mySource.[C_SHA256HashedMobilePhone]
     ,myTarget.[C_SFDC_Email_Activity_Flag___Last_30_Days1] = mySource.[C_SFDC_Email_Activity_Flag___Last_30_Days1]

WHEN NOT MATCHED BY SOURCE AND myTarget.ETL_IsDeleted = 0
THEN UPDATE SET
      myTarget.[ETL_UpdatedDate] = @RunTime
	 ,myTarget.[ETL_IsDeleted] = 1
	 ,myTarget.[ETL_DeletedDate] = @RunTime
     
WHEN NOT MATCHED BY TARGET
THEN INSERT
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ID]
     ,[Name]
     ,[AccountName]
     ,[BouncebackDate]
     ,[IsBounceback]
     ,[IsSubscribed]
     ,[PostalCode]
     ,[Province]
     ,[SubscriptionDate]
     ,[UnsubscriptionDate]
     ,[CreatedAt]
     ,[CreatedBy]
     ,[AccessedAt]
     ,[CurrentStatus]
     ,[Depth]
     ,[UpdatedAt]
     ,[UpdatedBy]
     ,[EmailAddress]
     ,[FirstName]
     ,[LastName]
     ,[Company]
     ,[Address1]
     ,[Address2]
     ,[Address3]
     ,[City]
     ,[Country]
     ,[MobilePhone]
     ,[BusinessPhone]
     ,[Fax]
     ,[Title]
     ,[SalesPerson]
     ,[C_EmailDisplayName]
     ,[C_State_Prov]
     ,[C_Zip_Postal]
     ,[C_Salutation]
     ,[C_Owner]
     ,[C_IDNumber]
     ,[C_Account]
     ,[C_SFDCContactID]
     ,[C_SFDCLeadID]
     ,[C_Website]
     ,[C_DateCreated]
     ,[C_DateModified]
     ,[C_SalesnetAccountID]
     ,[C_OptIn]
     ,[C_PermissionSource]
     ,[C_PermissionMedium]
     ,[C_PermissionDate]
     ,[ContactIDExt]
     ,[C_SFDCAccountID]
     ,[C_LastModifiedByExtIntegrateSystem]
     ,[C_SFDCLastCampaignID]
     ,[C_SFDCLastCampaignStatus]
     ,[C_SFDCLastCampaignName]
     ,[C_Last_Lead_Rating1]
     ,[C_Last_Lead_Score1]
     ,[C_Lead_Score___Historical_All_Time1]
     ,[C_Lead_Rating___Historical_All_Time__HAT_1]
     ,[C_Company_Revenue1]
     ,[C_Buying_Horizon1]
     ,[C_SFDC_EmailOptOut1]
     ,[C_MSCRMContactID]
     ,[C_MSCRMLeadID]
     ,[C_SiebelOnDemandContactID]
     ,[C_SiebelOnDemandLeadID]
     ,[C_SalesLogixContactID]
     ,[C_Lead_Source___Most_Recent1]
     ,[C_Lead_Source___Original1]
     ,[C_Industry1]
     ,[C_Annual_Revenue1]
     ,[C_Lead_Status1]
     ,[C_SFDC_Lead_Rating1]
     ,[C_SiebelOnDemandAccountID]
     ,[C_SalesLogixAccountID]
     ,[C_MSCRMAccountID]
     ,[C_Job_Role1]
     ,[C_Last_Website_Visit_Date_and_Time1]
     ,[C_LS___High_Value_Website_Content1]
     ,[C_NetSuiteContactID]
     ,[C_NetSuiteLeadID]
     ,[C_NetSuiteCompanyID]
     ,[C_DUNS_Number]
     ,[C_Doing_Business_As]
     ,[C_CEO_Name]
     ,[C_Industry]
     ,[C_SIC_Code]
     ,[C_Established_In]
     ,[C_Annual_Sales_Indicator]
     ,[C_Annual_Sales]
     ,[C_Total_Employees]
     ,[C_Total_Employees_Indicator]
     ,[C_StrikeIron_Country]
     ,[C_Business_Structure]
     ,[C_Lead_Score_Date___Most_Recent1]
     ,[C_Birth_Date1]
     ,[C_Number_Of_Tickets1]
     ,[C_Interest___Kings1]
     ,[C_Interest___Monarchs1]
     ,[C_Interest___Other_Sporting_Events1]
     ,[C_Interest___Family_Shows1]
     ,[C_Interest___Concerts1]
     ,[C_Archtics_Account_ID1]
     ,[C_Account_Type_Description1]
     ,[C_add_date1]
     ,[C_upd_datetime1]
     ,[C_Middle_Name1]
     ,[C_Evening_Phone1]
     ,[C_Customer_Status1]
     ,[C_Day_Phone1]
     ,[C_Product_Interest___Kings_Full_Season1]
     ,[C_Product_Interest___Kings_Partial_Season1]
     ,[C_Product_Interest___Kings_Group_Tickets1]
     ,[C_Product_Interest_Kings_Row_Tickets1]
     ,[C_Product_Interest___Kings_Suites1]
     ,[C_Temporary_Segment1]
     ,[C_Sub___MSE_News1]
     ,[C_Sub___MSE_Offers1]
     ,[C_Sub___AR_Com1]
     ,[C_Rep___Ticket_Services1]
     ,[C_Rep___Ticket_Services__email_1]
     ,[C_Rep___Ticket_Services__phone_1]
     ,[C_Rep___Group_Sales11]
     ,[C_Product_Interest___Kings_Individual1]
     ,[C_Lead_Scoring_Date1]
     ,[C_Zip_Code_Ty_e1]
     ,[C_Rep___Season_Sales11]
     ,[C_Rep___Premium_Sales1]
     ,[C_Interest___Business11]
     ,[C_LN___Timestamp11]
     ,[C_Premium_Product_Type1]
     ,[C_Birthday___This_Year13]
     ,[C__08Acq_More_Info11]
     ,[C__501_c__3__Fed_Tax_ID1]
     ,[C_Birthday___This_Year_PW1]
     ,[C_COPPA___Under_13_1]
     ,[C_How_to_Use_Tickets1]
     ,[C_Premium_Suite_Letter1]
     ,[C_TSSC_Temp_Field_1__MVP_Relo_Time_1]
     ,[C_ETW_Source1]
     ,[C_Rep___Partner_Business_Manager1]
     ,[C_TSSC_Temp_Field_33__STH_Commuinty_BBQ_Seg_1]
     ,[C_Lead_Rating___Monarchs1]
     ,[C_KG_Payment_Date1]
     ,[C_KG_Payment_Amount1]
     ,[C_KG_Payment_Card1]
     ,[C_KG_Payment_Multi_Card1]
     ,[C_Sharepartner_Flag1]
     ,[C_Sharepartner_Account_ID1]
     ,[C_Sharepartner_Team1]
     ,[C_Are_You_a_Total_Access_Member1]
     ,[C_TSSC_Temp_Field_54__09_Rod_Buyers_1]
     ,[C_EmailAddressDomain]
     ,[C_FirstAndLastName]
     ,[C_Favorite_Player__c_1]
     ,[C_Birth_Month1]
     ,[C_SFDC_last_7_day_activity_flag1]
     ,[C_SFDC_Last_Activity_Date1]
     ,[C_Engagement_Status1]
     ,[C_TSSC_Temp_Field_45__Relo_Select_a_Seat_time]
     ,[C_TSSC_Temp_Field_15__STH_Type_1]
     ,[C_TSSC_Temp_Field_04__GIN_1]
     ,[C_TSSC_Temp_Field_05__Open_House_Time_1]
     ,[C_TSSC_Temp_Field_09__ROTK_OPH_Time_1]
     ,[C_TSSC_Temp_Field_10__STH_Referral_Rep_1]
     ,[C_TSSC_Tem_Field_16__STH_Fan_Forums_1]
     ,[C_TSSC_Temp_Field_18__KBA_Rep_Vip_Invite_1]
     ,[C_Favorite_Match_Up_11]
     ,[C_Favorite_Match_Up_21]
     ,[C_Territory]
     ,[C_TSSC_Temp_Feild_16__CCK_PURL_Id_1]
     ,[C_TSSC_Temp_Field_2__KOL_Ticket_Link_1]
     ,[C_Lead_Source_Most_Recent]
     ,[C_Lead_Source_Original]
     ,[C_TSSC_Temp_Field__13KG_Renewal_Rep_1]
     ,[C_TSSC_Temp_Field_53__Segment_1]
     ,[C_Placeholder__FirstName_1]
     ,[C_Placeholder__LastName_1]
     ,[C_Opt_In_Source1]
     ,[C_Lead_Score]
     ,[C_ElqPURLName]
     ,[C_TSSC_Temp_Field__Rookie_Mini_Camp_1]
     ,[C_TSSC_Temp_Field_18__Temp_REP_Phone_1]
     ,[C_TSSC_Temp_Field_24__PD_Time_1]
     ,[C_TSSC_Temp_Field_25__PD_address_1]
     ,[C_SFDC_Kings_com_Activity_Flag1]
     ,[C_SFDC_ESC_com_Activity_Flag1]
     ,[C_MD5HashedEmailAddress]
     ,[C_SHA256HashedEmailAddress]
     ,[C_MD5HashedBusPhone]
     ,[C_SHA256HashedBusPhone]
     ,[C_MD5HashedMobilePhone]
     ,[C_SHA256HashedMobilePhone]
     ,[C_SFDC_Email_Activity_Flag___Last_30_Days1]
     )
VALUES
     (@RunTime --ETL_CreatedDate
     ,@RunTime --ETL_UpdateddDate
     ,0 --ETL_DeletedDate
     ,NULL --ETL_DeletedDate
     ,mySource.[ETL_DeltaHashKey]
     ,mySource.[ID]
     ,mySource.[Name]
     ,mySource.[AccountName]
     ,mySource.[BouncebackDate]
     ,mySource.[IsBounceback]
     ,mySource.[IsSubscribed]
     ,mySource.[PostalCode]
     ,mySource.[Province]
     ,mySource.[SubscriptionDate]
     ,mySource.[UnsubscriptionDate]
     ,mySource.[CreatedAt]
     ,mySource.[CreatedBy]
     ,mySource.[AccessedAt]
     ,mySource.[CurrentStatus]
     ,mySource.[Depth]
     ,mySource.[UpdatedAt]
     ,mySource.[UpdatedBy]
     ,mySource.[EmailAddress]
     ,mySource.[FirstName]
     ,mySource.[LastName]
     ,mySource.[Company]
     ,mySource.[Address1]
     ,mySource.[Address2]
     ,mySource.[Address3]
     ,mySource.[City]
     ,mySource.[Country]
     ,mySource.[MobilePhone]
     ,mySource.[BusinessPhone]
     ,mySource.[Fax]
     ,mySource.[Title]
     ,mySource.[SalesPerson]
     ,mySource.[C_EmailDisplayName]
     ,mySource.[C_State_Prov]
     ,mySource.[C_Zip_Postal]
     ,mySource.[C_Salutation]
     ,mySource.[C_Owner]
     ,mySource.[C_IDNumber]
     ,mySource.[C_Account]
     ,mySource.[C_SFDCContactID]
     ,mySource.[C_SFDCLeadID]
     ,mySource.[C_Website]
     ,mySource.[C_DateCreated]
     ,mySource.[C_DateModified]
     ,mySource.[C_SalesnetAccountID]
     ,mySource.[C_OptIn]
     ,mySource.[C_PermissionSource]
     ,mySource.[C_PermissionMedium]
     ,mySource.[C_PermissionDate]
     ,mySource.[ContactIDExt]
     ,mySource.[C_SFDCAccountID]
     ,mySource.[C_LastModifiedByExtIntegrateSystem]
     ,mySource.[C_SFDCLastCampaignID]
     ,mySource.[C_SFDCLastCampaignStatus]
     ,mySource.[C_SFDCLastCampaignName]
     ,mySource.[C_Last_Lead_Rating1]
     ,mySource.[C_Last_Lead_Score1]
     ,mySource.[C_Lead_Score___Historical_All_Time1]
     ,mySource.[C_Lead_Rating___Historical_All_Time__HAT_1]
     ,mySource.[C_Company_Revenue1]
     ,mySource.[C_Buying_Horizon1]
     ,mySource.[C_SFDC_EmailOptOut1]
     ,mySource.[C_MSCRMContactID]
     ,mySource.[C_MSCRMLeadID]
     ,mySource.[C_SiebelOnDemandContactID]
     ,mySource.[C_SiebelOnDemandLeadID]
     ,mySource.[C_SalesLogixContactID]
     ,mySource.[C_Lead_Source___Most_Recent1]
     ,mySource.[C_Lead_Source___Original1]
     ,mySource.[C_Industry1]
     ,mySource.[C_Annual_Revenue1]
     ,mySource.[C_Lead_Status1]
     ,mySource.[C_SFDC_Lead_Rating1]
     ,mySource.[C_SiebelOnDemandAccountID]
     ,mySource.[C_SalesLogixAccountID]
     ,mySource.[C_MSCRMAccountID]
     ,mySource.[C_Job_Role1]
     ,mySource.[C_Last_Website_Visit_Date_and_Time1]
     ,mySource.[C_LS___High_Value_Website_Content1]
     ,mySource.[C_NetSuiteContactID]
     ,mySource.[C_NetSuiteLeadID]
     ,mySource.[C_NetSuiteCompanyID]
     ,mySource.[C_DUNS_Number]
     ,mySource.[C_Doing_Business_As]
     ,mySource.[C_CEO_Name]
     ,mySource.[C_Industry]
     ,mySource.[C_SIC_Code]
     ,mySource.[C_Established_In]
     ,mySource.[C_Annual_Sales_Indicator]
     ,mySource.[C_Annual_Sales]
     ,mySource.[C_Total_Employees]
     ,mySource.[C_Total_Employees_Indicator]
     ,mySource.[C_StrikeIron_Country]
     ,mySource.[C_Business_Structure]
     ,mySource.[C_Lead_Score_Date___Most_Recent1]
     ,mySource.[C_Birth_Date1]
     ,mySource.[C_Number_Of_Tickets1]
     ,mySource.[C_Interest___Kings1]
     ,mySource.[C_Interest___Monarchs1]
     ,mySource.[C_Interest___Other_Sporting_Events1]
     ,mySource.[C_Interest___Family_Shows1]
     ,mySource.[C_Interest___Concerts1]
     ,mySource.[C_Archtics_Account_ID1]
     ,mySource.[C_Account_Type_Description1]
     ,mySource.[C_add_date1]
     ,mySource.[C_upd_datetime1]
     ,mySource.[C_Middle_Name1]
     ,mySource.[C_Evening_Phone1]
     ,mySource.[C_Customer_Status1]
     ,mySource.[C_Day_Phone1]
     ,mySource.[C_Product_Interest___Kings_Full_Season1]
     ,mySource.[C_Product_Interest___Kings_Partial_Season1]
     ,mySource.[C_Product_Interest___Kings_Group_Tickets1]
     ,mySource.[C_Product_Interest_Kings_Row_Tickets1]
     ,mySource.[C_Product_Interest___Kings_Suites1]
     ,mySource.[C_Temporary_Segment1]
     ,mySource.[C_Sub___MSE_News1]
     ,mySource.[C_Sub___MSE_Offers1]
     ,mySource.[C_Sub___AR_Com1]
     ,mySource.[C_Rep___Ticket_Services1]
     ,mySource.[C_Rep___Ticket_Services__email_1]
     ,mySource.[C_Rep___Ticket_Services__phone_1]
     ,mySource.[C_Rep___Group_Sales11]
     ,mySource.[C_Product_Interest___Kings_Individual1]
     ,mySource.[C_Lead_Scoring_Date1]
     ,mySource.[C_Zip_Code_Ty_e1]
     ,mySource.[C_Rep___Season_Sales11]
     ,mySource.[C_Rep___Premium_Sales1]
     ,mySource.[C_Interest___Business11]
     ,mySource.[C_LN___Timestamp11]
     ,mySource.[C_Premium_Product_Type1]
     ,mySource.[C_Birthday___This_Year13]
     ,mySource.[C__08Acq_More_Info11]
     ,mySource.[C__501_c__3__Fed_Tax_ID1]
     ,mySource.[C_Birthday___This_Year_PW1]
     ,mySource.[C_COPPA___Under_13_1]
     ,mySource.[C_How_to_Use_Tickets1]
     ,mySource.[C_Premium_Suite_Letter1]
     ,mySource.[C_TSSC_Temp_Field_1__MVP_Relo_Time_1]
     ,mySource.[C_ETW_Source1]
     ,mySource.[C_Rep___Partner_Business_Manager1]
     ,mySource.[C_TSSC_Temp_Field_33__STH_Commuinty_BBQ_Seg_1]
     ,mySource.[C_Lead_Rating___Monarchs1]
     ,mySource.[C_KG_Payment_Date1]
     ,mySource.[C_KG_Payment_Amount1]
     ,mySource.[C_KG_Payment_Card1]
     ,mySource.[C_KG_Payment_Multi_Card1]
     ,mySource.[C_Sharepartner_Flag1]
     ,mySource.[C_Sharepartner_Account_ID1]
     ,mySource.[C_Sharepartner_Team1]
     ,mySource.[C_Are_You_a_Total_Access_Member1]
     ,mySource.[C_TSSC_Temp_Field_54__09_Rod_Buyers_1]
     ,mySource.[C_EmailAddressDomain]
     ,mySource.[C_FirstAndLastName]
     ,mySource.[C_Favorite_Player__c_1]
     ,mySource.[C_Birth_Month1]
     ,mySource.[C_SFDC_last_7_day_activity_flag1]
     ,mySource.[C_SFDC_Last_Activity_Date1]
     ,mySource.[C_Engagement_Status1]
     ,mySource.[C_TSSC_Temp_Field_45__Relo_Select_a_Seat_time]
     ,mySource.[C_TSSC_Temp_Field_15__STH_Type_1]
     ,mySource.[C_TSSC_Temp_Field_04__GIN_1]
     ,mySource.[C_TSSC_Temp_Field_05__Open_House_Time_1]
     ,mySource.[C_TSSC_Temp_Field_09__ROTK_OPH_Time_1]
     ,mySource.[C_TSSC_Temp_Field_10__STH_Referral_Rep_1]
     ,mySource.[C_TSSC_Tem_Field_16__STH_Fan_Forums_1]
     ,mySource.[C_TSSC_Temp_Field_18__KBA_Rep_Vip_Invite_1]
     ,mySource.[C_Favorite_Match_Up_11]
     ,mySource.[C_Favorite_Match_Up_21]
     ,mySource.[C_Territory]
     ,mySource.[C_TSSC_Temp_Feild_16__CCK_PURL_Id_1]
     ,mysource.[C_TSSC_Temp_Field_2__KOL_Ticket_Link_1]
	 ,mysource.[C_Lead_Source_Most_Recent]
	 ,mysource.[C_Lead_Source_Original]
     ,mysource.[C_TSSC_Temp_Field__13KG_Renewal_Rep_1]
	 ,mysource.[C_TSSC_Temp_Field_53__Segment_1]
	 ,mysource.[C_Placeholder__FirstName_1]
	 ,mysource.[C_Placeholder__LastName_1]
	 ,mysource.[C_Opt_In_Source1]
	 ,mysource.[C_Lead_Score]
	 ,mysource.[C_ElqPURLName]
	 ,mysource.[C_TSSC_Temp_Field__Rookie_Mini_Camp_1]
	 ,mysource.[C_TSSC_Temp_Field_18__Temp_REP_Phone_1]
	 ,mysource.[C_TSSC_Temp_Field_24__PD_Time_1]
	 ,mysource.[C_TSSC_Temp_Field_25__PD_address_1]
	 ,mysource.[C_SFDC_Kings_com_Activity_Flag1]
	 ,mysource.[C_SFDC_ESC_com_Activity_Flag1]
	 ,mysource.[C_MD5HashedEmailAddress]
	 ,mysource.[C_SHA256HashedEmailAddress]
	 ,mysource.[C_MD5HashedBusPhone]
	 ,mysource.[C_SHA256HashedBusPhone]
	 ,mysource.[C_MD5HashedMobilePhone]
	 ,mysource.[C_SHA256HashedMobilePhone]
	 ,mysource.[C_SFDC_Email_Activity_Flag___Last_30_Days1]
)
;


DECLARE @MergeInsertRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM [ods].[Eloqua_Contact] WHERE ETL_CreatedDate >= @RunTime AND ETL_UpdatedDate = ETL_CreatedDate),'0');	
DECLARE @MergeUpdateRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM [ods].[Eloqua_Contact] WHERE ETL_UpdatedDate >= @RunTime AND ETL_UpdatedDate > ETL_CreatedDate),'0');	


END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)

END CATCH


END












GO
