SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [etl].[Load_ods_LiveAnalytics_Customer]
(
	@BatchId INT = 0,
	@Options NVARCHAR(MAX) = null
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     SSBCLOUD\dhorstman
Date:     07/01/2016
Comments: Initial creation
*************************************************************************************/

DECLARE @RunTime DATETIME = GETDATE()

DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName NVARCHAR(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM stg.LiveAnalytics_Customer),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0'

BEGIN TRY 

PRINT 'Execution Id: ' + CONVERT(NVARCHAR(100),@ExecutionId)

SELECT CAST(NULL AS BINARY(32)) ETL_DeltaHashKey, ult_party_id, party_id, acct_id, la_id, cust_first_nm, cust_middle_nm, cust_last_nm, cust_addr_line_1, cust_addr_line_2, cust_city_nm, cust_state_nm, cust_postal_cd, cust_ctry_nm, cust_phn_num_1, cust_phn_num_2, cust_email_addr, psx_classic_clus_cd, psx_group_id, psx_classic_prec_lvl_cd, discretionary_income_index_cd, income_est_hh_cd, hh_male_18_24_ind, hh_female_18_24_ind, hh_unk_18_24_ind, hh_male_25_34_ind, hh_female_25_34_ind, hh_unk_25_34_ind, hh_male_35_44_ind, hh_female_35_44_ind, hh_unk_35_44_ind, hh_male_45_54_ind, hh_female_45_54_ind, hh_unk_45_54_ind, hh_male_55_64_ind, hh_female_55_64_ind, hh_unk_55_64_ind, hh_male_65_74_ind, hh_female_65_74_ind, hh_unk_65_74_ind, hh_male_75_plus_ind, hh_female_75_plus_ind, hh_unk_75_plus_ind, age_two_yr_incr_1st_indv, age_two_yr_incr_2nd_indv, age_two_yr_incr_input_indv, veh_truck_owner_cd, veh_mtrcyc_owner_cd, veh_rv_owner_cd, veh_new_car_buyer_flg, veh_known_owned_cd, veh_dominant_lifestyle_cd, occpn_input_indv_cd, gndr_input_indv_cd, gndr_1st_indv_cd, gndr_2nd_indv_cd, edu_input_indv_cd, hh_male_00_02_ind, hh_female_00_02_ind, hh_unk_00_02_ind, hh_male_03_05_ind, hh_female_03_05_ind, hh_unk_03_05_ind, hh_male_06_10_ind, hh_female_06_10_ind, hh_unk_06_10_ind, hh_male_11_15_ind, hh_female_11_15_ind, hh_unk_11_15_ind, hh_male_16_17_ind, hh_female_16_17_ind, hh_unk_16_17_ind, occpn_1st_indv_cd, occpn_2nd_indv_cd, marital_status_hh_cd, wrk_wmn_hh_flg, presence_chldn_new_flg, adult_hh_num, edu_1st_indv_cd, edu_2nd_indv_cd, int_theatre_perf_arts_cd, int_arts_cd, int_travel_domestic_cd, int_home_stereo_cd, int_music_player_cd, int_music_avid_lstnr_cd, int_music_clctr_cd, int_movie_clctr_cd, int_auto_motor_racing_cd, int_spectator_sport_footb_cd, int_spectator_sport_baseb_cd, int_spectator_sport_bsktb_cd, int_spectator_sport_hockey_cd, int_spectator_sport_soccer_cd, int_spectator_sport_tennis_cd, int_swpstake_contest_cd, int_sports_grp_cd, int_music_grp_cd, int_nascar_cd, int_upscale_living_cd, int_cultural_living_cd, len_of_resdnc_cd, dwlng_type_cd, mail_ord_donor_cd, mail_ord_buyer_cd, mail_ord_respndr_cd, bank_card_hldr_cd, gas_dept_retail_card_hldr_cd, travel_ent_card_hldr_cd, credit_card_unk_type_hld_cd, prem_card_hldr_cd, upscale_dept_str_card_hldr_cd, infobase_pos_match_cd, acx_sources_num, acx_overall_match_cd, suprs_mail_dma_cd, client_event_cnt, client_tkt, client_sp, client_event_dt_min, client_event_dt_max, client_pe_tkt_cnt, client_pe_sp, client_tkt_price, client_tkt_price_max, client_presale_cnt, client_onsale_cnt, client_first_wk_cnt, client_inbetween_cnt, client_final_wk_cnt, client_tkt_price_000_025_cnt, client_tkt_price_026_050_cnt, client_tkt_price_051_100_cnt, client_tkt_price_101_200_cnt, client_tkt_price_201_plus_cnt, r3y_client_event_cnt, r3y_client_tkt_cnt, r3y_client_sp, r3y_client_pe_tkt, r3y_client_pe_sp, r3y_client_tkt_price, r1y_client_event_cnt, r1y_client_tkt_cnt, r1y_client_sp, r1y_client_pe_tkt, r1y_client_pe_sp, r1y_client_tkt_price, dist_to_client_ven, dist_to_client_event, sale_dt_max, event_dt_max, e3_tran_cnt, e3_event_cnt, e3_tkt_cnt, e3_tran_amt, py_tran_avg, py_event_avg, py_tkt_avg, py_tran_amt, pe_tran_avg, pe_tkt_avg, pe_tran_amt, tkt_price_avg, tkt_price_min, tkt_price_max, tkt_qty_purch_01_02_cnt, tkt_qty_purch_03_04_cnt, tkt_qty_purch_05_08_cnt, tkt_qty_purch_09_plus_cnt, tkt_price_000_025_cnt, tkt_price_026_050_cnt, tkt_price_051_100_cnt, tkt_price_101_200_cnt, tkt_price_201_plus_cnt, tkt_type_low_cnt, tkt_type_mid_cnt, tkt_type_high_cnt, tkt_type_super_cnt, tkt_type_vip_cnt, dist_to_ven, dist_to_ven_local, dist_000_010_ind, dist_011_025_ind, dist_026_050_ind, dist_051_100_ind, dist_101_200_ind, dist_201_plus_ind, prkg_ind, pmt_visa_ind, pmt_mastercard_ind, pmt_amex_ind, pmt_discover_ind, pmt_oth_ind, e3_chnl_inet_ind, e3_chnl_phn_ind, e3_dlvry_willcall_ind, e3_dlvry_ups_ind, e3_dlvry_ticketfast_ind, e3_dlvry_mail_ind, e3_dlvry_paperless_ind, e3_dlvry_oth_ind, purch_presale_ind, purch_onsale_ind, purch_first_wk_ind, purch_inbetween_ind, purch_final_wk_ind, m_concerts_presale_ind, m_concerts_first_dy_ind, m_concerts_first_wk_ind, m_concerts_inbetween_ind, m_concerts_final_wk_ind, m_arts_presale_ind, m_arts_first_dy_ind, m_arts_first_wk_ind, m_arts_inbetween_ind, m_arts_final_wk_ind, m_fmly_presale_ind, m_fmly_first_dy_ind, m_fmly_first_wk_ind, m_fmly_inbetween_ind, m_fmly_final_wk_ind, m_sports_presale_ind, m_sports_first_dy_ind, m_sports_first_wk_ind, m_sports_inbetween_ind, m_sports_final_wk_ind, e3_m_concerts_cnt, e3_m_arts_cnt, e3_m_fmly_cnt, e3_m_sports_cnt, e3_m_concerts_sp, e3_m_arts_sp, e3_m_fmly_sp, e3_m_sports_sp, py_m_concerts_cnt, py_m_arts_cnt, py_m_fmly_cnt, py_m_sports_cnt, py_m_concerts_sp, py_m_arts_sp, py_m_fmly_sp, py_m_sports_sp, pe_m_concerts_tkt, pe_m_arts_tkt, pe_m_fmly_tkt, pe_m_sports_tkt, pe_m_concerts_sp, pe_m_arts_sp, pe_m_family_sp, pe_m_sports_sp, pe_m_concerts_spi, pe_m_arts_spi, pe_m_fmly_spi, pe_m_sports_spi, mon_between_purch, mon_between_event, mon_since_last_event, mon_since_last_purch, r5_cd, f5_cd, m5_tkt_price_cd, m5_tkt_type_cd, brkr_ind, grp_buyer_ind, multi_tkt_16_plus_ind, grade_fm_cd, grade_rfm_cd, score_fm5, score_rfm5, e3_ms_a_brwymus_ind, e3_ms_a_comedy_ind, e3_ms_a_clasopera_ind, e3_ms_a_oth_ind, e3_ms_c_adultcont_ind, e3_ms_c_altrock_ind, e3_ms_c_ctry_ind, e3_ms_c_dancemus_ind, e3_ms_c_hardrock_ind, e3_ms_c_jazz_ind, e3_ms_c_latin_ind, e3_ms_c_hiphop_ind, e3_ms_c_rbsoul_ind, e3_ms_c_rockpop_ind, e3_ms_c_oth_ind, e3_ms_s_boxmmawres_ind, e3_ms_s_motor_ind, e3_ms_s_rodeo_ind, e3_ms_s_oth_ind, e3_ms_f_fmly_ind, propn_f_fmly, propn_a_brwymus, propn_a_arts_oth, propn_c_altrock, propn_c_comedy, propn_c_ctry, propn_c_hardrock, propn_c_jazz, propn_c_latin, propn_c_rbsoul, propn_c_rap, propn_c_rockpop, propn_c_oth, propn_s_baseb, propn_s_bsktb, propn_s_footb, propn_s_hockey, propn_s_motor, propn_s_sports_oth, r3y_event_cnt, r3y_tkt_cnt, r3y_tran_amt, r3y_pe_tkt, r3y_pe_tran_amt, r3y_tkt_price_avg, r3y_tkt_price_000_025_ind, r3y_tkt_price_026_050_ind, r3y_tkt_price_051_100_ind, r3y_tkt_price_101_200_ind, r3y_tkt_price_201_plus_ind, r3y_tkt_type_low_ind, r3y_tkt_type_mid_ind, r3y_tkt_type_high_ind, r3y_tkt_type_super_ind, r3y_tkt_type_vip_ind, r3y_dist_000_010_ind, r3y_dist_011_025_ind, r3y_dist_026_050_ind, r3y_dist_051_100_ind, r3y_dist_101_200_ind, r3y_dist_201_plus_ind, r3y_prkg_ind, r3y_ms_a_brwymus_ind, r3y_ms_a_comedy_ind, r3y_ms_a_clasopera_ind, r3y_ms_a_oth_ind, r3y_ms_c_adultcont_ind, r3y_ms_c_altrock_ind, r3y_ms_c_ctry_ind, r3y_ms_c_dancemus_ind, r3y_ms_c_hardrock_ind, r3y_ms_c_jazz_ind, r3y_ms_c_latin_ind, r3y_ms_c_hiphop_ind, r3y_ms_c_rbsoul_ind, r3y_ms_c_rockpop_ind, r3y_ms_c_oth_ind, r3y_ms_s_boxmmawres_ind, r3y_ms_s_motor_ind, r3y_ms_s_rodeo_ind, r3y_ms_s_oth_ind, r3y_ms_f_fmly_ind, race_cd, net_worth_gold_cd, est_hh_inc_higher_ranges_cd, est_hh_inc_narrow_ranges_cd, est_hh_inc_cd_100pct_inc_cd, est_hh_inc_cd_100pct_prec_cd, first_indv_first_nm, first_indv_md_nm, second_indv_first_nm, second_indv_md_nm, bo_out_sale_dt_min, bo_out_sale_dt_max, bo_out_event_dt_min, bo_out_event_dt_max, bo_out_tot_tran_amt, bo_out_pe_tran_amt, bo_out_tot_tran_cnt, bo_out_tot_event_cnt, bo_out_purch_dy_of_event_cnt, bo_out_purch_1_wk_before_cnt, bo_out_purch_2_wk_before_cnt, bo_out_purch_3_wk_before_cnt, bo_out_purch_4_wk_before_cnt, bo_out_purch_5_wk_before_cnt, bo_out_client_sale_dt_min, bo_out_client_sale_dt_max, bo_out_client_event_dt_min, bo_out_client_event_dt_max, bo_out_client_tot_tran_amt, bo_out_client_pe_tran_amt, bo_out_client_tot_event_cnt, bo_out_ven_sale_dt_min, bo_out_ven_sale_dt_max, bo_out_ven_event_dt_min, bo_out_ven_event_dt_max, bo_out_ven_tot_tran_amt, bo_out_ven_pe_tran_amt, bo_out_ven_tot_event_cnt, msa_nm
INTO #SrcData
FROM stg.LiveAnalytics_Customer

UPDATE #SrcData
SET ETL_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(acct_id),'DBNULL_TEXT') + ISNULL(RTRIM(acx_overall_match_cd),'DBNULL_TEXT') + ISNULL(RTRIM(acx_sources_num),'DBNULL_TEXT') + ISNULL(RTRIM(adult_hh_num),'DBNULL_TEXT') + ISNULL(RTRIM(age_two_yr_incr_1st_indv),'DBNULL_TEXT') + ISNULL(RTRIM(age_two_yr_incr_2nd_indv),'DBNULL_TEXT') + ISNULL(RTRIM(age_two_yr_incr_input_indv),'DBNULL_TEXT') + ISNULL(RTRIM(bank_card_hldr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_event_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_event_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_pe_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_sale_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_sale_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_tot_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_client_tot_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_event_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_event_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_pe_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_purch_1_wk_before_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_purch_2_wk_before_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_purch_3_wk_before_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_purch_4_wk_before_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_purch_5_wk_before_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_purch_dy_of_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_sale_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_sale_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_tot_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_tot_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_tot_tran_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_event_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_event_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_pe_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_sale_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_sale_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_tot_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(bo_out_ven_tot_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(brkr_ind),'DBNULL_TEXT') + ISNULL(RTRIM(client_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_event_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(client_event_dt_min),'DBNULL_TEXT') + ISNULL(RTRIM(client_final_wk_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_first_wk_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_inbetween_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_onsale_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_pe_sp),'DBNULL_TEXT') + ISNULL(RTRIM(client_pe_tkt_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_presale_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_sp),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price_000_025_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price_026_050_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price_051_100_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price_101_200_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price_201_plus_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(client_tkt_price_max),'DBNULL_TEXT') + ISNULL(RTRIM(credit_card_unk_type_hld_cd),'DBNULL_TEXT') + ISNULL(RTRIM(cust_addr_line_1),'DBNULL_TEXT') + ISNULL(RTRIM(cust_addr_line_2),'DBNULL_TEXT') + ISNULL(RTRIM(cust_city_nm),'DBNULL_TEXT') + ISNULL(RTRIM(cust_ctry_nm),'DBNULL_TEXT') + ISNULL(RTRIM(cust_email_addr),'DBNULL_TEXT') + ISNULL(RTRIM(cust_first_nm),'DBNULL_TEXT') + ISNULL(RTRIM(cust_last_nm),'DBNULL_TEXT') + ISNULL(RTRIM(cust_middle_nm),'DBNULL_TEXT') + ISNULL(RTRIM(cust_phn_num_1),'DBNULL_TEXT') + ISNULL(RTRIM(cust_phn_num_2),'DBNULL_TEXT') + ISNULL(RTRIM(cust_postal_cd),'DBNULL_TEXT') + ISNULL(RTRIM(cust_state_nm),'DBNULL_TEXT') + ISNULL(RTRIM(discretionary_income_index_cd),'DBNULL_TEXT') + ISNULL(RTRIM(dist_000_010_ind),'DBNULL_TEXT') + ISNULL(RTRIM(dist_011_025_ind),'DBNULL_TEXT') + ISNULL(RTRIM(dist_026_050_ind),'DBNULL_TEXT') + ISNULL(RTRIM(dist_051_100_ind),'DBNULL_TEXT') + ISNULL(RTRIM(dist_101_200_ind),'DBNULL_TEXT') + ISNULL(RTRIM(dist_201_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(dist_to_client_event),'DBNULL_TEXT') + ISNULL(RTRIM(dist_to_client_ven),'DBNULL_TEXT') + ISNULL(RTRIM(dist_to_ven),'DBNULL_TEXT') + ISNULL(RTRIM(dist_to_ven_local),'DBNULL_TEXT') + ISNULL(RTRIM(dwlng_type_cd),'DBNULL_TEXT') + ISNULL(RTRIM(e3_chnl_inet_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_chnl_phn_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_dlvry_mail_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_dlvry_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_dlvry_paperless_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_dlvry_ticketfast_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_dlvry_ups_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_dlvry_willcall_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_arts_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_arts_sp),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_concerts_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_concerts_sp),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_fmly_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_fmly_sp),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_sports_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_m_sports_sp),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_a_brwymus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_a_clasopera_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_a_comedy_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_a_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_adultcont_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_altrock_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_ctry_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_dancemus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_hardrock_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_hiphop_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_jazz_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_latin_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_rbsoul_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_c_rockpop_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_f_fmly_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_s_boxmmawres_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_s_motor_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_s_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_ms_s_rodeo_ind),'DBNULL_TEXT') + ISNULL(RTRIM(e3_tkt_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(e3_tran_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(edu_1st_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(edu_2nd_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(edu_input_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(est_hh_inc_cd_100pct_inc_cd),'DBNULL_TEXT') + ISNULL(RTRIM(est_hh_inc_cd_100pct_prec_cd),'DBNULL_TEXT') + ISNULL(RTRIM(est_hh_inc_higher_ranges_cd),'DBNULL_TEXT') + ISNULL(RTRIM(est_hh_inc_narrow_ranges_cd),'DBNULL_TEXT') + ISNULL(RTRIM(event_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(f5_cd),'DBNULL_TEXT') + ISNULL(RTRIM(first_indv_first_nm),'DBNULL_TEXT') + ISNULL(RTRIM(first_indv_md_nm),'DBNULL_TEXT') + ISNULL(RTRIM(gas_dept_retail_card_hldr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(gndr_1st_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(gndr_2nd_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(gndr_input_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(grade_fm_cd),'DBNULL_TEXT') + ISNULL(RTRIM(grade_rfm_cd),'DBNULL_TEXT') + ISNULL(RTRIM(grp_buyer_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_00_02_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_03_05_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_06_10_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_11_15_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_16_17_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_18_24_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_25_34_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_35_44_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_45_54_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_55_64_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_65_74_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_female_75_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_00_02_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_03_05_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_06_10_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_11_15_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_16_17_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_18_24_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_25_34_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_35_44_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_45_54_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_55_64_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_65_74_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_male_75_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_00_02_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_03_05_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_06_10_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_11_15_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_16_17_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_18_24_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_25_34_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_35_44_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_45_54_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_55_64_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_65_74_ind),'DBNULL_TEXT') + ISNULL(RTRIM(hh_unk_75_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(income_est_hh_cd),'DBNULL_TEXT') + ISNULL(RTRIM(infobase_pos_match_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_arts_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_auto_motor_racing_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_cultural_living_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_home_stereo_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_movie_clctr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_music_avid_lstnr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_music_clctr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_music_grp_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_music_player_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_nascar_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_spectator_sport_baseb_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_spectator_sport_bsktb_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_spectator_sport_footb_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_spectator_sport_hockey_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_spectator_sport_soccer_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_spectator_sport_tennis_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_sports_grp_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_swpstake_contest_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_theatre_perf_arts_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_travel_domestic_cd),'DBNULL_TEXT') + ISNULL(RTRIM(int_upscale_living_cd),'DBNULL_TEXT') + ISNULL(RTRIM(la_id),'DBNULL_TEXT') + ISNULL(RTRIM(len_of_resdnc_cd),'DBNULL_TEXT') + ISNULL(RTRIM(m_arts_final_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_arts_first_dy_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_arts_first_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_arts_inbetween_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_arts_presale_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_concerts_final_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_concerts_first_dy_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_concerts_first_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_concerts_inbetween_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_concerts_presale_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_fmly_final_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_fmly_first_dy_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_fmly_first_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_fmly_inbetween_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_fmly_presale_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_sports_final_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_sports_first_dy_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_sports_first_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_sports_inbetween_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m_sports_presale_ind),'DBNULL_TEXT') + ISNULL(RTRIM(m5_tkt_price_cd),'DBNULL_TEXT') + ISNULL(RTRIM(m5_tkt_type_cd),'DBNULL_TEXT') + ISNULL(RTRIM(mail_ord_buyer_cd),'DBNULL_TEXT') + ISNULL(RTRIM(mail_ord_donor_cd),'DBNULL_TEXT') + ISNULL(RTRIM(mail_ord_respndr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(marital_status_hh_cd),'DBNULL_TEXT') + ISNULL(RTRIM(mon_between_event),'DBNULL_TEXT') + ISNULL(RTRIM(mon_between_purch),'DBNULL_TEXT') + ISNULL(RTRIM(mon_since_last_event),'DBNULL_TEXT') + ISNULL(RTRIM(mon_since_last_purch),'DBNULL_TEXT') + ISNULL(RTRIM(msa_nm),'DBNULL_TEXT') + ISNULL(RTRIM(multi_tkt_16_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(net_worth_gold_cd),'DBNULL_TEXT') + ISNULL(RTRIM(occpn_1st_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(occpn_2nd_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(occpn_input_indv_cd),'DBNULL_TEXT') + ISNULL(RTRIM(party_id),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_arts_sp),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_arts_spi),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_arts_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_concerts_sp),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_concerts_spi),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_concerts_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_family_sp),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_fmly_spi),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_fmly_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_sports_sp),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_sports_spi),'DBNULL_TEXT') + ISNULL(RTRIM(pe_m_sports_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(pe_tkt_avg),'DBNULL_TEXT') + ISNULL(RTRIM(pe_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(pe_tran_avg),'DBNULL_TEXT') + ISNULL(RTRIM(pmt_amex_ind),'DBNULL_TEXT') + ISNULL(RTRIM(pmt_discover_ind),'DBNULL_TEXT') + ISNULL(RTRIM(pmt_mastercard_ind),'DBNULL_TEXT') + ISNULL(RTRIM(pmt_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(pmt_visa_ind),'DBNULL_TEXT') + ISNULL(RTRIM(prem_card_hldr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(presence_chldn_new_flg),'DBNULL_TEXT') + ISNULL(RTRIM(prkg_ind),'DBNULL_TEXT') + ISNULL(RTRIM(propn_a_arts_oth),'DBNULL_TEXT') + ISNULL(RTRIM(propn_a_brwymus),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_altrock),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_comedy),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_ctry),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_hardrock),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_jazz),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_latin),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_oth),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_rap),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_rbsoul),'DBNULL_TEXT') + ISNULL(RTRIM(propn_c_rockpop),'DBNULL_TEXT') + ISNULL(RTRIM(propn_f_fmly),'DBNULL_TEXT') + ISNULL(RTRIM(propn_s_baseb),'DBNULL_TEXT') + ISNULL(RTRIM(propn_s_bsktb),'DBNULL_TEXT') + ISNULL(RTRIM(propn_s_footb),'DBNULL_TEXT') + ISNULL(RTRIM(propn_s_hockey),'DBNULL_TEXT') + ISNULL(RTRIM(propn_s_motor),'DBNULL_TEXT') + ISNULL(RTRIM(propn_s_sports_oth),'DBNULL_TEXT') + ISNULL(RTRIM(psx_classic_clus_cd),'DBNULL_TEXT') + ISNULL(RTRIM(psx_classic_prec_lvl_cd),'DBNULL_TEXT') + ISNULL(RTRIM(psx_group_id),'DBNULL_TEXT') + ISNULL(RTRIM(purch_final_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(purch_first_wk_ind),'DBNULL_TEXT') + ISNULL(RTRIM(purch_inbetween_ind),'DBNULL_TEXT') + ISNULL(RTRIM(purch_onsale_ind),'DBNULL_TEXT') + ISNULL(RTRIM(purch_presale_ind),'DBNULL_TEXT') + ISNULL(RTRIM(py_event_avg),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_arts_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_arts_sp),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_concerts_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_concerts_sp),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_fmly_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_fmly_sp),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_sports_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(py_m_sports_sp),'DBNULL_TEXT') + ISNULL(RTRIM(py_tkt_avg),'DBNULL_TEXT') + ISNULL(RTRIM(py_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(py_tran_avg),'DBNULL_TEXT') + ISNULL(RTRIM(r1y_client_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(r1y_client_pe_sp),'DBNULL_TEXT') + ISNULL(RTRIM(r1y_client_pe_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(r1y_client_sp),'DBNULL_TEXT') + ISNULL(RTRIM(r1y_client_tkt_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(r1y_client_tkt_price),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_client_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_client_pe_sp),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_client_pe_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_client_sp),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_client_tkt_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_client_tkt_price),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_dist_000_010_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_dist_011_025_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_dist_026_050_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_dist_051_100_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_dist_101_200_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_dist_201_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_event_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_a_brwymus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_a_clasopera_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_a_comedy_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_a_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_adultcont_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_altrock_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_ctry_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_dancemus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_hardrock_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_hiphop_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_jazz_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_latin_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_rbsoul_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_c_rockpop_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_f_fmly_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_s_boxmmawres_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_s_motor_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_s_oth_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_ms_s_rodeo_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_pe_tkt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_pe_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_prkg_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_price_000_025_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_price_026_050_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_price_051_100_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_price_101_200_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_price_201_plus_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_price_avg),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_type_high_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_type_low_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_type_mid_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_type_super_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tkt_type_vip_ind),'DBNULL_TEXT') + ISNULL(RTRIM(r3y_tran_amt),'DBNULL_TEXT') + ISNULL(RTRIM(r5_cd),'DBNULL_TEXT') + ISNULL(RTRIM(race_cd),'DBNULL_TEXT') + ISNULL(RTRIM(sale_dt_max),'DBNULL_TEXT') + ISNULL(RTRIM(score_fm5),'DBNULL_TEXT') + ISNULL(RTRIM(score_rfm5),'DBNULL_TEXT') + ISNULL(RTRIM(second_indv_first_nm),'DBNULL_TEXT') + ISNULL(RTRIM(second_indv_md_nm),'DBNULL_TEXT') + ISNULL(RTRIM(suprs_mail_dma_cd),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_000_025_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_026_050_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_051_100_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_101_200_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_201_plus_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_avg),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_max),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_price_min),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_qty_purch_01_02_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_qty_purch_03_04_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_qty_purch_05_08_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_qty_purch_09_plus_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_type_high_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_type_low_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_type_mid_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_type_super_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(tkt_type_vip_cnt),'DBNULL_TEXT') + ISNULL(RTRIM(travel_ent_card_hldr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(ult_party_id),'DBNULL_TEXT') + ISNULL(RTRIM(upscale_dept_str_card_hldr_cd),'DBNULL_TEXT') + ISNULL(RTRIM(veh_dominant_lifestyle_cd),'DBNULL_TEXT') + ISNULL(RTRIM(veh_known_owned_cd),'DBNULL_TEXT') + ISNULL(RTRIM(veh_mtrcyc_owner_cd),'DBNULL_TEXT') + ISNULL(RTRIM(veh_new_car_buyer_flg),'DBNULL_TEXT') + ISNULL(RTRIM(veh_rv_owner_cd),'DBNULL_TEXT') + ISNULL(RTRIM(veh_truck_owner_cd),'DBNULL_TEXT') + ISNULL(RTRIM(wrk_wmn_hh_flg),'DBNULL_TEXT'))

CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (ult_party_id)
CREATE NONCLUSTERED INDEX IDX_ETL_DeltaHashKey ON #SrcData (ETL_DeltaHashKey)



MERGE ods.LiveAnalytics_Customer AS myTarget
USING (
	SELECT * FROM #SrcData
) AS mySource
ON myTarget.ult_party_id = mySource.ult_party_id
WHEN MATCHED AND (
     ISNULL(mySource.ETL_DeltaHashKey,-1) <> ISNULL(myTarget.ETL_DeltaHashKey, -1)
	 
)
THEN UPDATE SET
      myTarget.[ETL_UpdatedDate] = @RunTime
     ,myTarget.[ETL_DeltaHashKey] = mySource.[ETL_DeltaHashKey]
     ,myTarget.[ult_party_id] = mySource.[ult_party_id]
     ,myTarget.[party_id] = mySource.[party_id]
     ,myTarget.[acct_id] = mySource.[acct_id]
     ,myTarget.[la_id] = mySource.[la_id]
     ,myTarget.[cust_first_nm] = mySource.[cust_first_nm]
     ,myTarget.[cust_middle_nm] = mySource.[cust_middle_nm]
     ,myTarget.[cust_last_nm] = mySource.[cust_last_nm]
     ,myTarget.[cust_addr_line_1] = mySource.[cust_addr_line_1]
     ,myTarget.[cust_addr_line_2] = mySource.[cust_addr_line_2]
     ,myTarget.[cust_city_nm] = mySource.[cust_city_nm]
     ,myTarget.[cust_state_nm] = mySource.[cust_state_nm]
     ,myTarget.[cust_postal_cd] = mySource.[cust_postal_cd]
     ,myTarget.[cust_ctry_nm] = mySource.[cust_ctry_nm]
     ,myTarget.[cust_phn_num_1] = mySource.[cust_phn_num_1]
     ,myTarget.[cust_phn_num_2] = mySource.[cust_phn_num_2]
     ,myTarget.[cust_email_addr] = mySource.[cust_email_addr]
     ,myTarget.[psx_classic_clus_cd] = mySource.[psx_classic_clus_cd]
     ,myTarget.[psx_group_id] = mySource.[psx_group_id]
     ,myTarget.[psx_classic_prec_lvl_cd] = mySource.[psx_classic_prec_lvl_cd]
     ,myTarget.[discretionary_income_index_cd] = mySource.[discretionary_income_index_cd]
     ,myTarget.[income_est_hh_cd] = mySource.[income_est_hh_cd]
     ,myTarget.[hh_male_18_24_ind] = mySource.[hh_male_18_24_ind]
     ,myTarget.[hh_female_18_24_ind] = mySource.[hh_female_18_24_ind]
     ,myTarget.[hh_unk_18_24_ind] = mySource.[hh_unk_18_24_ind]
     ,myTarget.[hh_male_25_34_ind] = mySource.[hh_male_25_34_ind]
     ,myTarget.[hh_female_25_34_ind] = mySource.[hh_female_25_34_ind]
     ,myTarget.[hh_unk_25_34_ind] = mySource.[hh_unk_25_34_ind]
     ,myTarget.[hh_male_35_44_ind] = mySource.[hh_male_35_44_ind]
     ,myTarget.[hh_female_35_44_ind] = mySource.[hh_female_35_44_ind]
     ,myTarget.[hh_unk_35_44_ind] = mySource.[hh_unk_35_44_ind]
     ,myTarget.[hh_male_45_54_ind] = mySource.[hh_male_45_54_ind]
     ,myTarget.[hh_female_45_54_ind] = mySource.[hh_female_45_54_ind]
     ,myTarget.[hh_unk_45_54_ind] = mySource.[hh_unk_45_54_ind]
     ,myTarget.[hh_male_55_64_ind] = mySource.[hh_male_55_64_ind]
     ,myTarget.[hh_female_55_64_ind] = mySource.[hh_female_55_64_ind]
     ,myTarget.[hh_unk_55_64_ind] = mySource.[hh_unk_55_64_ind]
     ,myTarget.[hh_male_65_74_ind] = mySource.[hh_male_65_74_ind]
     ,myTarget.[hh_female_65_74_ind] = mySource.[hh_female_65_74_ind]
     ,myTarget.[hh_unk_65_74_ind] = mySource.[hh_unk_65_74_ind]
     ,myTarget.[hh_male_75_plus_ind] = mySource.[hh_male_75_plus_ind]
     ,myTarget.[hh_female_75_plus_ind] = mySource.[hh_female_75_plus_ind]
     ,myTarget.[hh_unk_75_plus_ind] = mySource.[hh_unk_75_plus_ind]
     ,myTarget.[age_two_yr_incr_1st_indv] = mySource.[age_two_yr_incr_1st_indv]
     ,myTarget.[age_two_yr_incr_2nd_indv] = mySource.[age_two_yr_incr_2nd_indv]
     ,myTarget.[age_two_yr_incr_input_indv] = mySource.[age_two_yr_incr_input_indv]
     ,myTarget.[veh_truck_owner_cd] = mySource.[veh_truck_owner_cd]
     ,myTarget.[veh_mtrcyc_owner_cd] = mySource.[veh_mtrcyc_owner_cd]
     ,myTarget.[veh_rv_owner_cd] = mySource.[veh_rv_owner_cd]
     ,myTarget.[veh_new_car_buyer_flg] = mySource.[veh_new_car_buyer_flg]
     ,myTarget.[veh_known_owned_cd] = mySource.[veh_known_owned_cd]
     ,myTarget.[veh_dominant_lifestyle_cd] = mySource.[veh_dominant_lifestyle_cd]
     ,myTarget.[occpn_input_indv_cd] = mySource.[occpn_input_indv_cd]
     ,myTarget.[gndr_input_indv_cd] = mySource.[gndr_input_indv_cd]
     ,myTarget.[gndr_1st_indv_cd] = mySource.[gndr_1st_indv_cd]
     ,myTarget.[gndr_2nd_indv_cd] = mySource.[gndr_2nd_indv_cd]
     ,myTarget.[edu_input_indv_cd] = mySource.[edu_input_indv_cd]
     ,myTarget.[hh_male_00_02_ind] = mySource.[hh_male_00_02_ind]
     ,myTarget.[hh_female_00_02_ind] = mySource.[hh_female_00_02_ind]
     ,myTarget.[hh_unk_00_02_ind] = mySource.[hh_unk_00_02_ind]
     ,myTarget.[hh_male_03_05_ind] = mySource.[hh_male_03_05_ind]
     ,myTarget.[hh_female_03_05_ind] = mySource.[hh_female_03_05_ind]
     ,myTarget.[hh_unk_03_05_ind] = mySource.[hh_unk_03_05_ind]
     ,myTarget.[hh_male_06_10_ind] = mySource.[hh_male_06_10_ind]
     ,myTarget.[hh_female_06_10_ind] = mySource.[hh_female_06_10_ind]
     ,myTarget.[hh_unk_06_10_ind] = mySource.[hh_unk_06_10_ind]
     ,myTarget.[hh_male_11_15_ind] = mySource.[hh_male_11_15_ind]
     ,myTarget.[hh_female_11_15_ind] = mySource.[hh_female_11_15_ind]
     ,myTarget.[hh_unk_11_15_ind] = mySource.[hh_unk_11_15_ind]
     ,myTarget.[hh_male_16_17_ind] = mySource.[hh_male_16_17_ind]
     ,myTarget.[hh_female_16_17_ind] = mySource.[hh_female_16_17_ind]
     ,myTarget.[hh_unk_16_17_ind] = mySource.[hh_unk_16_17_ind]
     ,myTarget.[occpn_1st_indv_cd] = mySource.[occpn_1st_indv_cd]
     ,myTarget.[occpn_2nd_indv_cd] = mySource.[occpn_2nd_indv_cd]
     ,myTarget.[marital_status_hh_cd] = mySource.[marital_status_hh_cd]
     ,myTarget.[wrk_wmn_hh_flg] = mySource.[wrk_wmn_hh_flg]
     ,myTarget.[presence_chldn_new_flg] = mySource.[presence_chldn_new_flg]
     ,myTarget.[adult_hh_num] = mySource.[adult_hh_num]
     ,myTarget.[edu_1st_indv_cd] = mySource.[edu_1st_indv_cd]
     ,myTarget.[edu_2nd_indv_cd] = mySource.[edu_2nd_indv_cd]
     ,myTarget.[int_theatre_perf_arts_cd] = mySource.[int_theatre_perf_arts_cd]
     ,myTarget.[int_arts_cd] = mySource.[int_arts_cd]
     ,myTarget.[int_travel_domestic_cd] = mySource.[int_travel_domestic_cd]
     ,myTarget.[int_home_stereo_cd] = mySource.[int_home_stereo_cd]
     ,myTarget.[int_music_player_cd] = mySource.[int_music_player_cd]
     ,myTarget.[int_music_avid_lstnr_cd] = mySource.[int_music_avid_lstnr_cd]
     ,myTarget.[int_music_clctr_cd] = mySource.[int_music_clctr_cd]
     ,myTarget.[int_movie_clctr_cd] = mySource.[int_movie_clctr_cd]
     ,myTarget.[int_auto_motor_racing_cd] = mySource.[int_auto_motor_racing_cd]
     ,myTarget.[int_spectator_sport_footb_cd] = mySource.[int_spectator_sport_footb_cd]
     ,myTarget.[int_spectator_sport_baseb_cd] = mySource.[int_spectator_sport_baseb_cd]
     ,myTarget.[int_spectator_sport_bsktb_cd] = mySource.[int_spectator_sport_bsktb_cd]
     ,myTarget.[int_spectator_sport_hockey_cd] = mySource.[int_spectator_sport_hockey_cd]
     ,myTarget.[int_spectator_sport_soccer_cd] = mySource.[int_spectator_sport_soccer_cd]
     ,myTarget.[int_spectator_sport_tennis_cd] = mySource.[int_spectator_sport_tennis_cd]
     ,myTarget.[int_swpstake_contest_cd] = mySource.[int_swpstake_contest_cd]
     ,myTarget.[int_sports_grp_cd] = mySource.[int_sports_grp_cd]
     ,myTarget.[int_music_grp_cd] = mySource.[int_music_grp_cd]
     ,myTarget.[int_nascar_cd] = mySource.[int_nascar_cd]
     ,myTarget.[int_upscale_living_cd] = mySource.[int_upscale_living_cd]
     ,myTarget.[int_cultural_living_cd] = mySource.[int_cultural_living_cd]
     ,myTarget.[len_of_resdnc_cd] = mySource.[len_of_resdnc_cd]
     ,myTarget.[dwlng_type_cd] = mySource.[dwlng_type_cd]
     ,myTarget.[mail_ord_donor_cd] = mySource.[mail_ord_donor_cd]
     ,myTarget.[mail_ord_buyer_cd] = mySource.[mail_ord_buyer_cd]
     ,myTarget.[mail_ord_respndr_cd] = mySource.[mail_ord_respndr_cd]
     ,myTarget.[bank_card_hldr_cd] = mySource.[bank_card_hldr_cd]
     ,myTarget.[gas_dept_retail_card_hldr_cd] = mySource.[gas_dept_retail_card_hldr_cd]
     ,myTarget.[travel_ent_card_hldr_cd] = mySource.[travel_ent_card_hldr_cd]
     ,myTarget.[credit_card_unk_type_hld_cd] = mySource.[credit_card_unk_type_hld_cd]
     ,myTarget.[prem_card_hldr_cd] = mySource.[prem_card_hldr_cd]
     ,myTarget.[upscale_dept_str_card_hldr_cd] = mySource.[upscale_dept_str_card_hldr_cd]
     ,myTarget.[infobase_pos_match_cd] = mySource.[infobase_pos_match_cd]
     ,myTarget.[acx_sources_num] = mySource.[acx_sources_num]
     ,myTarget.[acx_overall_match_cd] = mySource.[acx_overall_match_cd]
     ,myTarget.[suprs_mail_dma_cd] = mySource.[suprs_mail_dma_cd]
     ,myTarget.[client_event_cnt] = mySource.[client_event_cnt]
     ,myTarget.[client_tkt] = mySource.[client_tkt]
     ,myTarget.[client_sp] = mySource.[client_sp]
     ,myTarget.[client_event_dt_min] = mySource.[client_event_dt_min]
     ,myTarget.[client_event_dt_max] = mySource.[client_event_dt_max]
     ,myTarget.[client_pe_tkt_cnt] = mySource.[client_pe_tkt_cnt]
     ,myTarget.[client_pe_sp] = mySource.[client_pe_sp]
     ,myTarget.[client_tkt_price] = mySource.[client_tkt_price]
     ,myTarget.[client_tkt_price_max] = mySource.[client_tkt_price_max]
     ,myTarget.[client_presale_cnt] = mySource.[client_presale_cnt]
     ,myTarget.[client_onsale_cnt] = mySource.[client_onsale_cnt]
     ,myTarget.[client_first_wk_cnt] = mySource.[client_first_wk_cnt]
     ,myTarget.[client_inbetween_cnt] = mySource.[client_inbetween_cnt]
     ,myTarget.[client_final_wk_cnt] = mySource.[client_final_wk_cnt]
     ,myTarget.[client_tkt_price_000_025_cnt] = mySource.[client_tkt_price_000_025_cnt]
     ,myTarget.[client_tkt_price_026_050_cnt] = mySource.[client_tkt_price_026_050_cnt]
     ,myTarget.[client_tkt_price_051_100_cnt] = mySource.[client_tkt_price_051_100_cnt]
     ,myTarget.[client_tkt_price_101_200_cnt] = mySource.[client_tkt_price_101_200_cnt]
     ,myTarget.[client_tkt_price_201_plus_cnt] = mySource.[client_tkt_price_201_plus_cnt]
     ,myTarget.[r3y_client_event_cnt] = mySource.[r3y_client_event_cnt]
     ,myTarget.[r3y_client_tkt_cnt] = mySource.[r3y_client_tkt_cnt]
     ,myTarget.[r3y_client_sp] = mySource.[r3y_client_sp]
     ,myTarget.[r3y_client_pe_tkt] = mySource.[r3y_client_pe_tkt]
     ,myTarget.[r3y_client_pe_sp] = mySource.[r3y_client_pe_sp]
     ,myTarget.[r3y_client_tkt_price] = mySource.[r3y_client_tkt_price]
     ,myTarget.[r1y_client_event_cnt] = mySource.[r1y_client_event_cnt]
     ,myTarget.[r1y_client_tkt_cnt] = mySource.[r1y_client_tkt_cnt]
     ,myTarget.[r1y_client_sp] = mySource.[r1y_client_sp]
     ,myTarget.[r1y_client_pe_tkt] = mySource.[r1y_client_pe_tkt]
     ,myTarget.[r1y_client_pe_sp] = mySource.[r1y_client_pe_sp]
     ,myTarget.[r1y_client_tkt_price] = mySource.[r1y_client_tkt_price]
     ,myTarget.[dist_to_client_ven] = mySource.[dist_to_client_ven]
     ,myTarget.[dist_to_client_event] = mySource.[dist_to_client_event]
     ,myTarget.[sale_dt_max] = mySource.[sale_dt_max]
     ,myTarget.[event_dt_max] = mySource.[event_dt_max]
     ,myTarget.[e3_tran_cnt] = mySource.[e3_tran_cnt]
     ,myTarget.[e3_event_cnt] = mySource.[e3_event_cnt]
     ,myTarget.[e3_tkt_cnt] = mySource.[e3_tkt_cnt]
     ,myTarget.[e3_tran_amt] = mySource.[e3_tran_amt]
     ,myTarget.[py_tran_avg] = mySource.[py_tran_avg]
     ,myTarget.[py_event_avg] = mySource.[py_event_avg]
     ,myTarget.[py_tkt_avg] = mySource.[py_tkt_avg]
     ,myTarget.[py_tran_amt] = mySource.[py_tran_amt]
     ,myTarget.[pe_tran_avg] = mySource.[pe_tran_avg]
     ,myTarget.[pe_tkt_avg] = mySource.[pe_tkt_avg]
     ,myTarget.[pe_tran_amt] = mySource.[pe_tran_amt]
     ,myTarget.[tkt_price_avg] = mySource.[tkt_price_avg]
     ,myTarget.[tkt_price_min] = mySource.[tkt_price_min]
     ,myTarget.[tkt_price_max] = mySource.[tkt_price_max]
     ,myTarget.[tkt_qty_purch_01_02_cnt] = mySource.[tkt_qty_purch_01_02_cnt]
     ,myTarget.[tkt_qty_purch_03_04_cnt] = mySource.[tkt_qty_purch_03_04_cnt]
     ,myTarget.[tkt_qty_purch_05_08_cnt] = mySource.[tkt_qty_purch_05_08_cnt]
     ,myTarget.[tkt_qty_purch_09_plus_cnt] = mySource.[tkt_qty_purch_09_plus_cnt]
     ,myTarget.[tkt_price_000_025_cnt] = mySource.[tkt_price_000_025_cnt]
     ,myTarget.[tkt_price_026_050_cnt] = mySource.[tkt_price_026_050_cnt]
     ,myTarget.[tkt_price_051_100_cnt] = mySource.[tkt_price_051_100_cnt]
     ,myTarget.[tkt_price_101_200_cnt] = mySource.[tkt_price_101_200_cnt]
     ,myTarget.[tkt_price_201_plus_cnt] = mySource.[tkt_price_201_plus_cnt]
     ,myTarget.[tkt_type_low_cnt] = mySource.[tkt_type_low_cnt]
     ,myTarget.[tkt_type_mid_cnt] = mySource.[tkt_type_mid_cnt]
     ,myTarget.[tkt_type_high_cnt] = mySource.[tkt_type_high_cnt]
     ,myTarget.[tkt_type_super_cnt] = mySource.[tkt_type_super_cnt]
     ,myTarget.[tkt_type_vip_cnt] = mySource.[tkt_type_vip_cnt]
     ,myTarget.[dist_to_ven] = mySource.[dist_to_ven]
     ,myTarget.[dist_to_ven_local] = mySource.[dist_to_ven_local]
     ,myTarget.[dist_000_010_ind] = mySource.[dist_000_010_ind]
     ,myTarget.[dist_011_025_ind] = mySource.[dist_011_025_ind]
     ,myTarget.[dist_026_050_ind] = mySource.[dist_026_050_ind]
     ,myTarget.[dist_051_100_ind] = mySource.[dist_051_100_ind]
     ,myTarget.[dist_101_200_ind] = mySource.[dist_101_200_ind]
     ,myTarget.[dist_201_plus_ind] = mySource.[dist_201_plus_ind]
     ,myTarget.[prkg_ind] = mySource.[prkg_ind]
     ,myTarget.[pmt_visa_ind] = mySource.[pmt_visa_ind]
     ,myTarget.[pmt_mastercard_ind] = mySource.[pmt_mastercard_ind]
     ,myTarget.[pmt_amex_ind] = mySource.[pmt_amex_ind]
     ,myTarget.[pmt_discover_ind] = mySource.[pmt_discover_ind]
     ,myTarget.[pmt_oth_ind] = mySource.[pmt_oth_ind]
     ,myTarget.[e3_chnl_inet_ind] = mySource.[e3_chnl_inet_ind]
     ,myTarget.[e3_chnl_phn_ind] = mySource.[e3_chnl_phn_ind]
     ,myTarget.[e3_dlvry_willcall_ind] = mySource.[e3_dlvry_willcall_ind]
     ,myTarget.[e3_dlvry_ups_ind] = mySource.[e3_dlvry_ups_ind]
     ,myTarget.[e3_dlvry_ticketfast_ind] = mySource.[e3_dlvry_ticketfast_ind]
     ,myTarget.[e3_dlvry_mail_ind] = mySource.[e3_dlvry_mail_ind]
     ,myTarget.[e3_dlvry_paperless_ind] = mySource.[e3_dlvry_paperless_ind]
     ,myTarget.[e3_dlvry_oth_ind] = mySource.[e3_dlvry_oth_ind]
     ,myTarget.[purch_presale_ind] = mySource.[purch_presale_ind]
     ,myTarget.[purch_onsale_ind] = mySource.[purch_onsale_ind]
     ,myTarget.[purch_first_wk_ind] = mySource.[purch_first_wk_ind]
     ,myTarget.[purch_inbetween_ind] = mySource.[purch_inbetween_ind]
     ,myTarget.[purch_final_wk_ind] = mySource.[purch_final_wk_ind]
     ,myTarget.[m_concerts_presale_ind] = mySource.[m_concerts_presale_ind]
     ,myTarget.[m_concerts_first_dy_ind] = mySource.[m_concerts_first_dy_ind]
     ,myTarget.[m_concerts_first_wk_ind] = mySource.[m_concerts_first_wk_ind]
     ,myTarget.[m_concerts_inbetween_ind] = mySource.[m_concerts_inbetween_ind]
     ,myTarget.[m_concerts_final_wk_ind] = mySource.[m_concerts_final_wk_ind]
     ,myTarget.[m_arts_presale_ind] = mySource.[m_arts_presale_ind]
     ,myTarget.[m_arts_first_dy_ind] = mySource.[m_arts_first_dy_ind]
     ,myTarget.[m_arts_first_wk_ind] = mySource.[m_arts_first_wk_ind]
     ,myTarget.[m_arts_inbetween_ind] = mySource.[m_arts_inbetween_ind]
     ,myTarget.[m_arts_final_wk_ind] = mySource.[m_arts_final_wk_ind]
     ,myTarget.[m_fmly_presale_ind] = mySource.[m_fmly_presale_ind]
     ,myTarget.[m_fmly_first_dy_ind] = mySource.[m_fmly_first_dy_ind]
     ,myTarget.[m_fmly_first_wk_ind] = mySource.[m_fmly_first_wk_ind]
     ,myTarget.[m_fmly_inbetween_ind] = mySource.[m_fmly_inbetween_ind]
     ,myTarget.[m_fmly_final_wk_ind] = mySource.[m_fmly_final_wk_ind]
     ,myTarget.[m_sports_presale_ind] = mySource.[m_sports_presale_ind]
     ,myTarget.[m_sports_first_dy_ind] = mySource.[m_sports_first_dy_ind]
     ,myTarget.[m_sports_first_wk_ind] = mySource.[m_sports_first_wk_ind]
     ,myTarget.[m_sports_inbetween_ind] = mySource.[m_sports_inbetween_ind]
     ,myTarget.[m_sports_final_wk_ind] = mySource.[m_sports_final_wk_ind]
     ,myTarget.[e3_m_concerts_cnt] = mySource.[e3_m_concerts_cnt]
     ,myTarget.[e3_m_arts_cnt] = mySource.[e3_m_arts_cnt]
     ,myTarget.[e3_m_fmly_cnt] = mySource.[e3_m_fmly_cnt]
     ,myTarget.[e3_m_sports_cnt] = mySource.[e3_m_sports_cnt]
     ,myTarget.[e3_m_concerts_sp] = mySource.[e3_m_concerts_sp]
     ,myTarget.[e3_m_arts_sp] = mySource.[e3_m_arts_sp]
     ,myTarget.[e3_m_fmly_sp] = mySource.[e3_m_fmly_sp]
     ,myTarget.[e3_m_sports_sp] = mySource.[e3_m_sports_sp]
     ,myTarget.[py_m_concerts_cnt] = mySource.[py_m_concerts_cnt]
     ,myTarget.[py_m_arts_cnt] = mySource.[py_m_arts_cnt]
     ,myTarget.[py_m_fmly_cnt] = mySource.[py_m_fmly_cnt]
     ,myTarget.[py_m_sports_cnt] = mySource.[py_m_sports_cnt]
     ,myTarget.[py_m_concerts_sp] = mySource.[py_m_concerts_sp]
     ,myTarget.[py_m_arts_sp] = mySource.[py_m_arts_sp]
     ,myTarget.[py_m_fmly_sp] = mySource.[py_m_fmly_sp]
     ,myTarget.[py_m_sports_sp] = mySource.[py_m_sports_sp]
     ,myTarget.[pe_m_concerts_tkt] = mySource.[pe_m_concerts_tkt]
     ,myTarget.[pe_m_arts_tkt] = mySource.[pe_m_arts_tkt]
     ,myTarget.[pe_m_fmly_tkt] = mySource.[pe_m_fmly_tkt]
     ,myTarget.[pe_m_sports_tkt] = mySource.[pe_m_sports_tkt]
     ,myTarget.[pe_m_concerts_sp] = mySource.[pe_m_concerts_sp]
     ,myTarget.[pe_m_arts_sp] = mySource.[pe_m_arts_sp]
     ,myTarget.[pe_m_family_sp] = mySource.[pe_m_family_sp]
     ,myTarget.[pe_m_sports_sp] = mySource.[pe_m_sports_sp]
     ,myTarget.[pe_m_concerts_spi] = mySource.[pe_m_concerts_spi]
     ,myTarget.[pe_m_arts_spi] = mySource.[pe_m_arts_spi]
     ,myTarget.[pe_m_fmly_spi] = mySource.[pe_m_fmly_spi]
     ,myTarget.[pe_m_sports_spi] = mySource.[pe_m_sports_spi]
     ,myTarget.[mon_between_purch] = mySource.[mon_between_purch]
     ,myTarget.[mon_between_event] = mySource.[mon_between_event]
     ,myTarget.[mon_since_last_event] = mySource.[mon_since_last_event]
     ,myTarget.[mon_since_last_purch] = mySource.[mon_since_last_purch]
     ,myTarget.[r5_cd] = mySource.[r5_cd]
     ,myTarget.[f5_cd] = mySource.[f5_cd]
     ,myTarget.[m5_tkt_price_cd] = mySource.[m5_tkt_price_cd]
     ,myTarget.[m5_tkt_type_cd] = mySource.[m5_tkt_type_cd]
     ,myTarget.[brkr_ind] = mySource.[brkr_ind]
     ,myTarget.[grp_buyer_ind] = mySource.[grp_buyer_ind]
     ,myTarget.[multi_tkt_16_plus_ind] = mySource.[multi_tkt_16_plus_ind]
     ,myTarget.[grade_fm_cd] = mySource.[grade_fm_cd]
     ,myTarget.[grade_rfm_cd] = mySource.[grade_rfm_cd]
     ,myTarget.[score_fm5] = mySource.[score_fm5]
     ,myTarget.[score_rfm5] = mySource.[score_rfm5]
     ,myTarget.[e3_ms_a_brwymus_ind] = mySource.[e3_ms_a_brwymus_ind]
     ,myTarget.[e3_ms_a_comedy_ind] = mySource.[e3_ms_a_comedy_ind]
     ,myTarget.[e3_ms_a_clasopera_ind] = mySource.[e3_ms_a_clasopera_ind]
     ,myTarget.[e3_ms_a_oth_ind] = mySource.[e3_ms_a_oth_ind]
     ,myTarget.[e3_ms_c_adultcont_ind] = mySource.[e3_ms_c_adultcont_ind]
     ,myTarget.[e3_ms_c_altrock_ind] = mySource.[e3_ms_c_altrock_ind]
     ,myTarget.[e3_ms_c_ctry_ind] = mySource.[e3_ms_c_ctry_ind]
     ,myTarget.[e3_ms_c_dancemus_ind] = mySource.[e3_ms_c_dancemus_ind]
     ,myTarget.[e3_ms_c_hardrock_ind] = mySource.[e3_ms_c_hardrock_ind]
     ,myTarget.[e3_ms_c_jazz_ind] = mySource.[e3_ms_c_jazz_ind]
     ,myTarget.[e3_ms_c_latin_ind] = mySource.[e3_ms_c_latin_ind]
     ,myTarget.[e3_ms_c_hiphop_ind] = mySource.[e3_ms_c_hiphop_ind]
     ,myTarget.[e3_ms_c_rbsoul_ind] = mySource.[e3_ms_c_rbsoul_ind]
     ,myTarget.[e3_ms_c_rockpop_ind] = mySource.[e3_ms_c_rockpop_ind]
     ,myTarget.[e3_ms_c_oth_ind] = mySource.[e3_ms_c_oth_ind]
     ,myTarget.[e3_ms_s_boxmmawres_ind] = mySource.[e3_ms_s_boxmmawres_ind]
     ,myTarget.[e3_ms_s_motor_ind] = mySource.[e3_ms_s_motor_ind]
     ,myTarget.[e3_ms_s_rodeo_ind] = mySource.[e3_ms_s_rodeo_ind]
     ,myTarget.[e3_ms_s_oth_ind] = mySource.[e3_ms_s_oth_ind]
     ,myTarget.[e3_ms_f_fmly_ind] = mySource.[e3_ms_f_fmly_ind]
     ,myTarget.[propn_f_fmly] = mySource.[propn_f_fmly]
     ,myTarget.[propn_a_brwymus] = mySource.[propn_a_brwymus]
     ,myTarget.[propn_a_arts_oth] = mySource.[propn_a_arts_oth]
     ,myTarget.[propn_c_altrock] = mySource.[propn_c_altrock]
     ,myTarget.[propn_c_comedy] = mySource.[propn_c_comedy]
     ,myTarget.[propn_c_ctry] = mySource.[propn_c_ctry]
     ,myTarget.[propn_c_hardrock] = mySource.[propn_c_hardrock]
     ,myTarget.[propn_c_jazz] = mySource.[propn_c_jazz]
     ,myTarget.[propn_c_latin] = mySource.[propn_c_latin]
     ,myTarget.[propn_c_rbsoul] = mySource.[propn_c_rbsoul]
     ,myTarget.[propn_c_rap] = mySource.[propn_c_rap]
     ,myTarget.[propn_c_rockpop] = mySource.[propn_c_rockpop]
     ,myTarget.[propn_c_oth] = mySource.[propn_c_oth]
     ,myTarget.[propn_s_baseb] = mySource.[propn_s_baseb]
     ,myTarget.[propn_s_bsktb] = mySource.[propn_s_bsktb]
     ,myTarget.[propn_s_footb] = mySource.[propn_s_footb]
     ,myTarget.[propn_s_hockey] = mySource.[propn_s_hockey]
     ,myTarget.[propn_s_motor] = mySource.[propn_s_motor]
     ,myTarget.[propn_s_sports_oth] = mySource.[propn_s_sports_oth]
     ,myTarget.[r3y_event_cnt] = mySource.[r3y_event_cnt]
     ,myTarget.[r3y_tkt_cnt] = mySource.[r3y_tkt_cnt]
     ,myTarget.[r3y_tran_amt] = mySource.[r3y_tran_amt]
     ,myTarget.[r3y_pe_tkt] = mySource.[r3y_pe_tkt]
     ,myTarget.[r3y_pe_tran_amt] = mySource.[r3y_pe_tran_amt]
     ,myTarget.[r3y_tkt_price_avg] = mySource.[r3y_tkt_price_avg]
     ,myTarget.[r3y_tkt_price_000_025_ind] = mySource.[r3y_tkt_price_000_025_ind]
     ,myTarget.[r3y_tkt_price_026_050_ind] = mySource.[r3y_tkt_price_026_050_ind]
     ,myTarget.[r3y_tkt_price_051_100_ind] = mySource.[r3y_tkt_price_051_100_ind]
     ,myTarget.[r3y_tkt_price_101_200_ind] = mySource.[r3y_tkt_price_101_200_ind]
     ,myTarget.[r3y_tkt_price_201_plus_ind] = mySource.[r3y_tkt_price_201_plus_ind]
     ,myTarget.[r3y_tkt_type_low_ind] = mySource.[r3y_tkt_type_low_ind]
     ,myTarget.[r3y_tkt_type_mid_ind] = mySource.[r3y_tkt_type_mid_ind]
     ,myTarget.[r3y_tkt_type_high_ind] = mySource.[r3y_tkt_type_high_ind]
     ,myTarget.[r3y_tkt_type_super_ind] = mySource.[r3y_tkt_type_super_ind]
     ,myTarget.[r3y_tkt_type_vip_ind] = mySource.[r3y_tkt_type_vip_ind]
     ,myTarget.[r3y_dist_000_010_ind] = mySource.[r3y_dist_000_010_ind]
     ,myTarget.[r3y_dist_011_025_ind] = mySource.[r3y_dist_011_025_ind]
     ,myTarget.[r3y_dist_026_050_ind] = mySource.[r3y_dist_026_050_ind]
     ,myTarget.[r3y_dist_051_100_ind] = mySource.[r3y_dist_051_100_ind]
     ,myTarget.[r3y_dist_101_200_ind] = mySource.[r3y_dist_101_200_ind]
     ,myTarget.[r3y_dist_201_plus_ind] = mySource.[r3y_dist_201_plus_ind]
     ,myTarget.[r3y_prkg_ind] = mySource.[r3y_prkg_ind]
     ,myTarget.[r3y_ms_a_brwymus_ind] = mySource.[r3y_ms_a_brwymus_ind]
     ,myTarget.[r3y_ms_a_comedy_ind] = mySource.[r3y_ms_a_comedy_ind]
     ,myTarget.[r3y_ms_a_clasopera_ind] = mySource.[r3y_ms_a_clasopera_ind]
     ,myTarget.[r3y_ms_a_oth_ind] = mySource.[r3y_ms_a_oth_ind]
     ,myTarget.[r3y_ms_c_adultcont_ind] = mySource.[r3y_ms_c_adultcont_ind]
     ,myTarget.[r3y_ms_c_altrock_ind] = mySource.[r3y_ms_c_altrock_ind]
     ,myTarget.[r3y_ms_c_ctry_ind] = mySource.[r3y_ms_c_ctry_ind]
     ,myTarget.[r3y_ms_c_dancemus_ind] = mySource.[r3y_ms_c_dancemus_ind]
     ,myTarget.[r3y_ms_c_hardrock_ind] = mySource.[r3y_ms_c_hardrock_ind]
     ,myTarget.[r3y_ms_c_jazz_ind] = mySource.[r3y_ms_c_jazz_ind]
     ,myTarget.[r3y_ms_c_latin_ind] = mySource.[r3y_ms_c_latin_ind]
     ,myTarget.[r3y_ms_c_hiphop_ind] = mySource.[r3y_ms_c_hiphop_ind]
     ,myTarget.[r3y_ms_c_rbsoul_ind] = mySource.[r3y_ms_c_rbsoul_ind]
     ,myTarget.[r3y_ms_c_rockpop_ind] = mySource.[r3y_ms_c_rockpop_ind]
     ,myTarget.[r3y_ms_c_oth_ind] = mySource.[r3y_ms_c_oth_ind]
     ,myTarget.[r3y_ms_s_boxmmawres_ind] = mySource.[r3y_ms_s_boxmmawres_ind]
     ,myTarget.[r3y_ms_s_motor_ind] = mySource.[r3y_ms_s_motor_ind]
     ,myTarget.[r3y_ms_s_rodeo_ind] = mySource.[r3y_ms_s_rodeo_ind]
     ,myTarget.[r3y_ms_s_oth_ind] = mySource.[r3y_ms_s_oth_ind]
     ,myTarget.[r3y_ms_f_fmly_ind] = mySource.[r3y_ms_f_fmly_ind]
     ,myTarget.[race_cd] = mySource.[race_cd]
     ,myTarget.[net_worth_gold_cd] = mySource.[net_worth_gold_cd]
     ,myTarget.[est_hh_inc_higher_ranges_cd] = mySource.[est_hh_inc_higher_ranges_cd]
     ,myTarget.[est_hh_inc_narrow_ranges_cd] = mySource.[est_hh_inc_narrow_ranges_cd]
     ,myTarget.[est_hh_inc_cd_100pct_inc_cd] = mySource.[est_hh_inc_cd_100pct_inc_cd]
     ,myTarget.[est_hh_inc_cd_100pct_prec_cd] = mySource.[est_hh_inc_cd_100pct_prec_cd]
     ,myTarget.[first_indv_first_nm] = mySource.[first_indv_first_nm]
     ,myTarget.[first_indv_md_nm] = mySource.[first_indv_md_nm]
     ,myTarget.[second_indv_first_nm] = mySource.[second_indv_first_nm]
     ,myTarget.[second_indv_md_nm] = mySource.[second_indv_md_nm]
     ,myTarget.[bo_out_sale_dt_min] = mySource.[bo_out_sale_dt_min]
     ,myTarget.[bo_out_sale_dt_max] = mySource.[bo_out_sale_dt_max]
     ,myTarget.[bo_out_event_dt_min] = mySource.[bo_out_event_dt_min]
     ,myTarget.[bo_out_event_dt_max] = mySource.[bo_out_event_dt_max]
     ,myTarget.[bo_out_tot_tran_amt] = mySource.[bo_out_tot_tran_amt]
     ,myTarget.[bo_out_pe_tran_amt] = mySource.[bo_out_pe_tran_amt]
     ,myTarget.[bo_out_tot_tran_cnt] = mySource.[bo_out_tot_tran_cnt]
     ,myTarget.[bo_out_tot_event_cnt] = mySource.[bo_out_tot_event_cnt]
     ,myTarget.[bo_out_purch_dy_of_event_cnt] = mySource.[bo_out_purch_dy_of_event_cnt]
     ,myTarget.[bo_out_purch_1_wk_before_cnt] = mySource.[bo_out_purch_1_wk_before_cnt]
     ,myTarget.[bo_out_purch_2_wk_before_cnt] = mySource.[bo_out_purch_2_wk_before_cnt]
     ,myTarget.[bo_out_purch_3_wk_before_cnt] = mySource.[bo_out_purch_3_wk_before_cnt]
     ,myTarget.[bo_out_purch_4_wk_before_cnt] = mySource.[bo_out_purch_4_wk_before_cnt]
     ,myTarget.[bo_out_purch_5_wk_before_cnt] = mySource.[bo_out_purch_5_wk_before_cnt]
     ,myTarget.[bo_out_client_sale_dt_min] = mySource.[bo_out_client_sale_dt_min]
     ,myTarget.[bo_out_client_sale_dt_max] = mySource.[bo_out_client_sale_dt_max]
     ,myTarget.[bo_out_client_event_dt_min] = mySource.[bo_out_client_event_dt_min]
     ,myTarget.[bo_out_client_event_dt_max] = mySource.[bo_out_client_event_dt_max]
     ,myTarget.[bo_out_client_tot_tran_amt] = mySource.[bo_out_client_tot_tran_amt]
     ,myTarget.[bo_out_client_pe_tran_amt] = mySource.[bo_out_client_pe_tran_amt]
     ,myTarget.[bo_out_client_tot_event_cnt] = mySource.[bo_out_client_tot_event_cnt]
     ,myTarget.[bo_out_ven_sale_dt_min] = mySource.[bo_out_ven_sale_dt_min]
     ,myTarget.[bo_out_ven_sale_dt_max] = mySource.[bo_out_ven_sale_dt_max]
     ,myTarget.[bo_out_ven_event_dt_min] = mySource.[bo_out_ven_event_dt_min]
     ,myTarget.[bo_out_ven_event_dt_max] = mySource.[bo_out_ven_event_dt_max]
     ,myTarget.[bo_out_ven_tot_tran_amt] = mySource.[bo_out_ven_tot_tran_amt]
     ,myTarget.[bo_out_ven_pe_tran_amt] = mySource.[bo_out_ven_pe_tran_amt]
     ,myTarget.[bo_out_ven_tot_event_cnt] = mySource.[bo_out_ven_tot_event_cnt]
     ,myTarget.[msa_nm] = mySource.[msa_nm]



WHEN NOT MATCHED BY TARGET
THEN INSERT
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ult_party_id]
     ,[party_id]
     ,[acct_id]
     ,[la_id]
     ,[cust_first_nm]
     ,[cust_middle_nm]
     ,[cust_last_nm]
     ,[cust_addr_line_1]
     ,[cust_addr_line_2]
     ,[cust_city_nm]
     ,[cust_state_nm]
     ,[cust_postal_cd]
     ,[cust_ctry_nm]
     ,[cust_phn_num_1]
     ,[cust_phn_num_2]
     ,[cust_email_addr]
     ,[psx_classic_clus_cd]
     ,[psx_group_id]
     ,[psx_classic_prec_lvl_cd]
     ,[discretionary_income_index_cd]
     ,[income_est_hh_cd]
     ,[hh_male_18_24_ind]
     ,[hh_female_18_24_ind]
     ,[hh_unk_18_24_ind]
     ,[hh_male_25_34_ind]
     ,[hh_female_25_34_ind]
     ,[hh_unk_25_34_ind]
     ,[hh_male_35_44_ind]
     ,[hh_female_35_44_ind]
     ,[hh_unk_35_44_ind]
     ,[hh_male_45_54_ind]
     ,[hh_female_45_54_ind]
     ,[hh_unk_45_54_ind]
     ,[hh_male_55_64_ind]
     ,[hh_female_55_64_ind]
     ,[hh_unk_55_64_ind]
     ,[hh_male_65_74_ind]
     ,[hh_female_65_74_ind]
     ,[hh_unk_65_74_ind]
     ,[hh_male_75_plus_ind]
     ,[hh_female_75_plus_ind]
     ,[hh_unk_75_plus_ind]
     ,[age_two_yr_incr_1st_indv]
     ,[age_two_yr_incr_2nd_indv]
     ,[age_two_yr_incr_input_indv]
     ,[veh_truck_owner_cd]
     ,[veh_mtrcyc_owner_cd]
     ,[veh_rv_owner_cd]
     ,[veh_new_car_buyer_flg]
     ,[veh_known_owned_cd]
     ,[veh_dominant_lifestyle_cd]
     ,[occpn_input_indv_cd]
     ,[gndr_input_indv_cd]
     ,[gndr_1st_indv_cd]
     ,[gndr_2nd_indv_cd]
     ,[edu_input_indv_cd]
     ,[hh_male_00_02_ind]
     ,[hh_female_00_02_ind]
     ,[hh_unk_00_02_ind]
     ,[hh_male_03_05_ind]
     ,[hh_female_03_05_ind]
     ,[hh_unk_03_05_ind]
     ,[hh_male_06_10_ind]
     ,[hh_female_06_10_ind]
     ,[hh_unk_06_10_ind]
     ,[hh_male_11_15_ind]
     ,[hh_female_11_15_ind]
     ,[hh_unk_11_15_ind]
     ,[hh_male_16_17_ind]
     ,[hh_female_16_17_ind]
     ,[hh_unk_16_17_ind]
     ,[occpn_1st_indv_cd]
     ,[occpn_2nd_indv_cd]
     ,[marital_status_hh_cd]
     ,[wrk_wmn_hh_flg]
     ,[presence_chldn_new_flg]
     ,[adult_hh_num]
     ,[edu_1st_indv_cd]
     ,[edu_2nd_indv_cd]
     ,[int_theatre_perf_arts_cd]
     ,[int_arts_cd]
     ,[int_travel_domestic_cd]
     ,[int_home_stereo_cd]
     ,[int_music_player_cd]
     ,[int_music_avid_lstnr_cd]
     ,[int_music_clctr_cd]
     ,[int_movie_clctr_cd]
     ,[int_auto_motor_racing_cd]
     ,[int_spectator_sport_footb_cd]
     ,[int_spectator_sport_baseb_cd]
     ,[int_spectator_sport_bsktb_cd]
     ,[int_spectator_sport_hockey_cd]
     ,[int_spectator_sport_soccer_cd]
     ,[int_spectator_sport_tennis_cd]
     ,[int_swpstake_contest_cd]
     ,[int_sports_grp_cd]
     ,[int_music_grp_cd]
     ,[int_nascar_cd]
     ,[int_upscale_living_cd]
     ,[int_cultural_living_cd]
     ,[len_of_resdnc_cd]
     ,[dwlng_type_cd]
     ,[mail_ord_donor_cd]
     ,[mail_ord_buyer_cd]
     ,[mail_ord_respndr_cd]
     ,[bank_card_hldr_cd]
     ,[gas_dept_retail_card_hldr_cd]
     ,[travel_ent_card_hldr_cd]
     ,[credit_card_unk_type_hld_cd]
     ,[prem_card_hldr_cd]
     ,[upscale_dept_str_card_hldr_cd]
     ,[infobase_pos_match_cd]
     ,[acx_sources_num]
     ,[acx_overall_match_cd]
     ,[suprs_mail_dma_cd]
     ,[client_event_cnt]
     ,[client_tkt]
     ,[client_sp]
     ,[client_event_dt_min]
     ,[client_event_dt_max]
     ,[client_pe_tkt_cnt]
     ,[client_pe_sp]
     ,[client_tkt_price]
     ,[client_tkt_price_max]
     ,[client_presale_cnt]
     ,[client_onsale_cnt]
     ,[client_first_wk_cnt]
     ,[client_inbetween_cnt]
     ,[client_final_wk_cnt]
     ,[client_tkt_price_000_025_cnt]
     ,[client_tkt_price_026_050_cnt]
     ,[client_tkt_price_051_100_cnt]
     ,[client_tkt_price_101_200_cnt]
     ,[client_tkt_price_201_plus_cnt]
     ,[r3y_client_event_cnt]
     ,[r3y_client_tkt_cnt]
     ,[r3y_client_sp]
     ,[r3y_client_pe_tkt]
     ,[r3y_client_pe_sp]
     ,[r3y_client_tkt_price]
     ,[r1y_client_event_cnt]
     ,[r1y_client_tkt_cnt]
     ,[r1y_client_sp]
     ,[r1y_client_pe_tkt]
     ,[r1y_client_pe_sp]
     ,[r1y_client_tkt_price]
     ,[dist_to_client_ven]
     ,[dist_to_client_event]
     ,[sale_dt_max]
     ,[event_dt_max]
     ,[e3_tran_cnt]
     ,[e3_event_cnt]
     ,[e3_tkt_cnt]
     ,[e3_tran_amt]
     ,[py_tran_avg]
     ,[py_event_avg]
     ,[py_tkt_avg]
     ,[py_tran_amt]
     ,[pe_tran_avg]
     ,[pe_tkt_avg]
     ,[pe_tran_amt]
     ,[tkt_price_avg]
     ,[tkt_price_min]
     ,[tkt_price_max]
     ,[tkt_qty_purch_01_02_cnt]
     ,[tkt_qty_purch_03_04_cnt]
     ,[tkt_qty_purch_05_08_cnt]
     ,[tkt_qty_purch_09_plus_cnt]
     ,[tkt_price_000_025_cnt]
     ,[tkt_price_026_050_cnt]
     ,[tkt_price_051_100_cnt]
     ,[tkt_price_101_200_cnt]
     ,[tkt_price_201_plus_cnt]
     ,[tkt_type_low_cnt]
     ,[tkt_type_mid_cnt]
     ,[tkt_type_high_cnt]
     ,[tkt_type_super_cnt]
     ,[tkt_type_vip_cnt]
     ,[dist_to_ven]
     ,[dist_to_ven_local]
     ,[dist_000_010_ind]
     ,[dist_011_025_ind]
     ,[dist_026_050_ind]
     ,[dist_051_100_ind]
     ,[dist_101_200_ind]
     ,[dist_201_plus_ind]
     ,[prkg_ind]
     ,[pmt_visa_ind]
     ,[pmt_mastercard_ind]
     ,[pmt_amex_ind]
     ,[pmt_discover_ind]
     ,[pmt_oth_ind]
     ,[e3_chnl_inet_ind]
     ,[e3_chnl_phn_ind]
     ,[e3_dlvry_willcall_ind]
     ,[e3_dlvry_ups_ind]
     ,[e3_dlvry_ticketfast_ind]
     ,[e3_dlvry_mail_ind]
     ,[e3_dlvry_paperless_ind]
     ,[e3_dlvry_oth_ind]
     ,[purch_presale_ind]
     ,[purch_onsale_ind]
     ,[purch_first_wk_ind]
     ,[purch_inbetween_ind]
     ,[purch_final_wk_ind]
     ,[m_concerts_presale_ind]
     ,[m_concerts_first_dy_ind]
     ,[m_concerts_first_wk_ind]
     ,[m_concerts_inbetween_ind]
     ,[m_concerts_final_wk_ind]
     ,[m_arts_presale_ind]
     ,[m_arts_first_dy_ind]
     ,[m_arts_first_wk_ind]
     ,[m_arts_inbetween_ind]
     ,[m_arts_final_wk_ind]
     ,[m_fmly_presale_ind]
     ,[m_fmly_first_dy_ind]
     ,[m_fmly_first_wk_ind]
     ,[m_fmly_inbetween_ind]
     ,[m_fmly_final_wk_ind]
     ,[m_sports_presale_ind]
     ,[m_sports_first_dy_ind]
     ,[m_sports_first_wk_ind]
     ,[m_sports_inbetween_ind]
     ,[m_sports_final_wk_ind]
     ,[e3_m_concerts_cnt]
     ,[e3_m_arts_cnt]
     ,[e3_m_fmly_cnt]
     ,[e3_m_sports_cnt]
     ,[e3_m_concerts_sp]
     ,[e3_m_arts_sp]
     ,[e3_m_fmly_sp]
     ,[e3_m_sports_sp]
     ,[py_m_concerts_cnt]
     ,[py_m_arts_cnt]
     ,[py_m_fmly_cnt]
     ,[py_m_sports_cnt]
     ,[py_m_concerts_sp]
     ,[py_m_arts_sp]
     ,[py_m_fmly_sp]
     ,[py_m_sports_sp]
     ,[pe_m_concerts_tkt]
     ,[pe_m_arts_tkt]
     ,[pe_m_fmly_tkt]
     ,[pe_m_sports_tkt]
     ,[pe_m_concerts_sp]
     ,[pe_m_arts_sp]
     ,[pe_m_family_sp]
     ,[pe_m_sports_sp]
     ,[pe_m_concerts_spi]
     ,[pe_m_arts_spi]
     ,[pe_m_fmly_spi]
     ,[pe_m_sports_spi]
     ,[mon_between_purch]
     ,[mon_between_event]
     ,[mon_since_last_event]
     ,[mon_since_last_purch]
     ,[r5_cd]
     ,[f5_cd]
     ,[m5_tkt_price_cd]
     ,[m5_tkt_type_cd]
     ,[brkr_ind]
     ,[grp_buyer_ind]
     ,[multi_tkt_16_plus_ind]
     ,[grade_fm_cd]
     ,[grade_rfm_cd]
     ,[score_fm5]
     ,[score_rfm5]
     ,[e3_ms_a_brwymus_ind]
     ,[e3_ms_a_comedy_ind]
     ,[e3_ms_a_clasopera_ind]
     ,[e3_ms_a_oth_ind]
     ,[e3_ms_c_adultcont_ind]
     ,[e3_ms_c_altrock_ind]
     ,[e3_ms_c_ctry_ind]
     ,[e3_ms_c_dancemus_ind]
     ,[e3_ms_c_hardrock_ind]
     ,[e3_ms_c_jazz_ind]
     ,[e3_ms_c_latin_ind]
     ,[e3_ms_c_hiphop_ind]
     ,[e3_ms_c_rbsoul_ind]
     ,[e3_ms_c_rockpop_ind]
     ,[e3_ms_c_oth_ind]
     ,[e3_ms_s_boxmmawres_ind]
     ,[e3_ms_s_motor_ind]
     ,[e3_ms_s_rodeo_ind]
     ,[e3_ms_s_oth_ind]
     ,[e3_ms_f_fmly_ind]
     ,[propn_f_fmly]
     ,[propn_a_brwymus]
     ,[propn_a_arts_oth]
     ,[propn_c_altrock]
     ,[propn_c_comedy]
     ,[propn_c_ctry]
     ,[propn_c_hardrock]
     ,[propn_c_jazz]
     ,[propn_c_latin]
     ,[propn_c_rbsoul]
     ,[propn_c_rap]
     ,[propn_c_rockpop]
     ,[propn_c_oth]
     ,[propn_s_baseb]
     ,[propn_s_bsktb]
     ,[propn_s_footb]
     ,[propn_s_hockey]
     ,[propn_s_motor]
     ,[propn_s_sports_oth]
     ,[r3y_event_cnt]
     ,[r3y_tkt_cnt]
     ,[r3y_tran_amt]
     ,[r3y_pe_tkt]
     ,[r3y_pe_tran_amt]
     ,[r3y_tkt_price_avg]
     ,[r3y_tkt_price_000_025_ind]
     ,[r3y_tkt_price_026_050_ind]
     ,[r3y_tkt_price_051_100_ind]
     ,[r3y_tkt_price_101_200_ind]
     ,[r3y_tkt_price_201_plus_ind]
     ,[r3y_tkt_type_low_ind]
     ,[r3y_tkt_type_mid_ind]
     ,[r3y_tkt_type_high_ind]
     ,[r3y_tkt_type_super_ind]
     ,[r3y_tkt_type_vip_ind]
     ,[r3y_dist_000_010_ind]
     ,[r3y_dist_011_025_ind]
     ,[r3y_dist_026_050_ind]
     ,[r3y_dist_051_100_ind]
     ,[r3y_dist_101_200_ind]
     ,[r3y_dist_201_plus_ind]
     ,[r3y_prkg_ind]
     ,[r3y_ms_a_brwymus_ind]
     ,[r3y_ms_a_comedy_ind]
     ,[r3y_ms_a_clasopera_ind]
     ,[r3y_ms_a_oth_ind]
     ,[r3y_ms_c_adultcont_ind]
     ,[r3y_ms_c_altrock_ind]
     ,[r3y_ms_c_ctry_ind]
     ,[r3y_ms_c_dancemus_ind]
     ,[r3y_ms_c_hardrock_ind]
     ,[r3y_ms_c_jazz_ind]
     ,[r3y_ms_c_latin_ind]
     ,[r3y_ms_c_hiphop_ind]
     ,[r3y_ms_c_rbsoul_ind]
     ,[r3y_ms_c_rockpop_ind]
     ,[r3y_ms_c_oth_ind]
     ,[r3y_ms_s_boxmmawres_ind]
     ,[r3y_ms_s_motor_ind]
     ,[r3y_ms_s_rodeo_ind]
     ,[r3y_ms_s_oth_ind]
     ,[r3y_ms_f_fmly_ind]
     ,[race_cd]
     ,[net_worth_gold_cd]
     ,[est_hh_inc_higher_ranges_cd]
     ,[est_hh_inc_narrow_ranges_cd]
     ,[est_hh_inc_cd_100pct_inc_cd]
     ,[est_hh_inc_cd_100pct_prec_cd]
     ,[first_indv_first_nm]
     ,[first_indv_md_nm]
     ,[second_indv_first_nm]
     ,[second_indv_md_nm]
     ,[bo_out_sale_dt_min]
     ,[bo_out_sale_dt_max]
     ,[bo_out_event_dt_min]
     ,[bo_out_event_dt_max]
     ,[bo_out_tot_tran_amt]
     ,[bo_out_pe_tran_amt]
     ,[bo_out_tot_tran_cnt]
     ,[bo_out_tot_event_cnt]
     ,[bo_out_purch_dy_of_event_cnt]
     ,[bo_out_purch_1_wk_before_cnt]
     ,[bo_out_purch_2_wk_before_cnt]
     ,[bo_out_purch_3_wk_before_cnt]
     ,[bo_out_purch_4_wk_before_cnt]
     ,[bo_out_purch_5_wk_before_cnt]
     ,[bo_out_client_sale_dt_min]
     ,[bo_out_client_sale_dt_max]
     ,[bo_out_client_event_dt_min]
     ,[bo_out_client_event_dt_max]
     ,[bo_out_client_tot_tran_amt]
     ,[bo_out_client_pe_tran_amt]
     ,[bo_out_client_tot_event_cnt]
     ,[bo_out_ven_sale_dt_min]
     ,[bo_out_ven_sale_dt_max]
     ,[bo_out_ven_event_dt_min]
     ,[bo_out_ven_event_dt_max]
     ,[bo_out_ven_tot_tran_amt]
     ,[bo_out_ven_pe_tran_amt]
     ,[bo_out_ven_tot_event_cnt]
     ,[msa_nm]
     )
VALUES
     (@RunTime --ETL_CreatedDate
     ,@RunTime --ETL_UpdateddDate
     ,0 --ETL_IsDeleted
     ,NULL --ETL_DeletedDate
     ,mySource.[ETL_DeltaHashKey]
     ,mySource.[ult_party_id]
     ,mySource.[party_id]
     ,mySource.[acct_id]
     ,mySource.[la_id]
     ,mySource.[cust_first_nm]
     ,mySource.[cust_middle_nm]
     ,mySource.[cust_last_nm]
     ,mySource.[cust_addr_line_1]
     ,mySource.[cust_addr_line_2]
     ,mySource.[cust_city_nm]
     ,mySource.[cust_state_nm]
     ,mySource.[cust_postal_cd]
     ,mySource.[cust_ctry_nm]
     ,mySource.[cust_phn_num_1]
     ,mySource.[cust_phn_num_2]
     ,mySource.[cust_email_addr]
     ,mySource.[psx_classic_clus_cd]
     ,mySource.[psx_group_id]
     ,mySource.[psx_classic_prec_lvl_cd]
     ,mySource.[discretionary_income_index_cd]
     ,mySource.[income_est_hh_cd]
     ,mySource.[hh_male_18_24_ind]
     ,mySource.[hh_female_18_24_ind]
     ,mySource.[hh_unk_18_24_ind]
     ,mySource.[hh_male_25_34_ind]
     ,mySource.[hh_female_25_34_ind]
     ,mySource.[hh_unk_25_34_ind]
     ,mySource.[hh_male_35_44_ind]
     ,mySource.[hh_female_35_44_ind]
     ,mySource.[hh_unk_35_44_ind]
     ,mySource.[hh_male_45_54_ind]
     ,mySource.[hh_female_45_54_ind]
     ,mySource.[hh_unk_45_54_ind]
     ,mySource.[hh_male_55_64_ind]
     ,mySource.[hh_female_55_64_ind]
     ,mySource.[hh_unk_55_64_ind]
     ,mySource.[hh_male_65_74_ind]
     ,mySource.[hh_female_65_74_ind]
     ,mySource.[hh_unk_65_74_ind]
     ,mySource.[hh_male_75_plus_ind]
     ,mySource.[hh_female_75_plus_ind]
     ,mySource.[hh_unk_75_plus_ind]
     ,mySource.[age_two_yr_incr_1st_indv]
     ,mySource.[age_two_yr_incr_2nd_indv]
     ,mySource.[age_two_yr_incr_input_indv]
     ,mySource.[veh_truck_owner_cd]
     ,mySource.[veh_mtrcyc_owner_cd]
     ,mySource.[veh_rv_owner_cd]
     ,mySource.[veh_new_car_buyer_flg]
     ,mySource.[veh_known_owned_cd]
     ,mySource.[veh_dominant_lifestyle_cd]
     ,mySource.[occpn_input_indv_cd]
     ,mySource.[gndr_input_indv_cd]
     ,mySource.[gndr_1st_indv_cd]
     ,mySource.[gndr_2nd_indv_cd]
     ,mySource.[edu_input_indv_cd]
     ,mySource.[hh_male_00_02_ind]
     ,mySource.[hh_female_00_02_ind]
     ,mySource.[hh_unk_00_02_ind]
     ,mySource.[hh_male_03_05_ind]
     ,mySource.[hh_female_03_05_ind]
     ,mySource.[hh_unk_03_05_ind]
     ,mySource.[hh_male_06_10_ind]
     ,mySource.[hh_female_06_10_ind]
     ,mySource.[hh_unk_06_10_ind]
     ,mySource.[hh_male_11_15_ind]
     ,mySource.[hh_female_11_15_ind]
     ,mySource.[hh_unk_11_15_ind]
     ,mySource.[hh_male_16_17_ind]
     ,mySource.[hh_female_16_17_ind]
     ,mySource.[hh_unk_16_17_ind]
     ,mySource.[occpn_1st_indv_cd]
     ,mySource.[occpn_2nd_indv_cd]
     ,mySource.[marital_status_hh_cd]
     ,mySource.[wrk_wmn_hh_flg]
     ,mySource.[presence_chldn_new_flg]
     ,mySource.[adult_hh_num]
     ,mySource.[edu_1st_indv_cd]
     ,mySource.[edu_2nd_indv_cd]
     ,mySource.[int_theatre_perf_arts_cd]
     ,mySource.[int_arts_cd]
     ,mySource.[int_travel_domestic_cd]
     ,mySource.[int_home_stereo_cd]
     ,mySource.[int_music_player_cd]
     ,mySource.[int_music_avid_lstnr_cd]
     ,mySource.[int_music_clctr_cd]
     ,mySource.[int_movie_clctr_cd]
     ,mySource.[int_auto_motor_racing_cd]
     ,mySource.[int_spectator_sport_footb_cd]
     ,mySource.[int_spectator_sport_baseb_cd]
     ,mySource.[int_spectator_sport_bsktb_cd]
     ,mySource.[int_spectator_sport_hockey_cd]
     ,mySource.[int_spectator_sport_soccer_cd]
     ,mySource.[int_spectator_sport_tennis_cd]
     ,mySource.[int_swpstake_contest_cd]
     ,mySource.[int_sports_grp_cd]
     ,mySource.[int_music_grp_cd]
     ,mySource.[int_nascar_cd]
     ,mySource.[int_upscale_living_cd]
     ,mySource.[int_cultural_living_cd]
     ,mySource.[len_of_resdnc_cd]
     ,mySource.[dwlng_type_cd]
     ,mySource.[mail_ord_donor_cd]
     ,mySource.[mail_ord_buyer_cd]
     ,mySource.[mail_ord_respndr_cd]
     ,mySource.[bank_card_hldr_cd]
     ,mySource.[gas_dept_retail_card_hldr_cd]
     ,mySource.[travel_ent_card_hldr_cd]
     ,mySource.[credit_card_unk_type_hld_cd]
     ,mySource.[prem_card_hldr_cd]
     ,mySource.[upscale_dept_str_card_hldr_cd]
     ,mySource.[infobase_pos_match_cd]
     ,mySource.[acx_sources_num]
     ,mySource.[acx_overall_match_cd]
     ,mySource.[suprs_mail_dma_cd]
     ,mySource.[client_event_cnt]
     ,mySource.[client_tkt]
     ,mySource.[client_sp]
     ,mySource.[client_event_dt_min]
     ,mySource.[client_event_dt_max]
     ,mySource.[client_pe_tkt_cnt]
     ,mySource.[client_pe_sp]
     ,mySource.[client_tkt_price]
     ,mySource.[client_tkt_price_max]
     ,mySource.[client_presale_cnt]
     ,mySource.[client_onsale_cnt]
     ,mySource.[client_first_wk_cnt]
     ,mySource.[client_inbetween_cnt]
     ,mySource.[client_final_wk_cnt]
     ,mySource.[client_tkt_price_000_025_cnt]
     ,mySource.[client_tkt_price_026_050_cnt]
     ,mySource.[client_tkt_price_051_100_cnt]
     ,mySource.[client_tkt_price_101_200_cnt]
     ,mySource.[client_tkt_price_201_plus_cnt]
     ,mySource.[r3y_client_event_cnt]
     ,mySource.[r3y_client_tkt_cnt]
     ,mySource.[r3y_client_sp]
     ,mySource.[r3y_client_pe_tkt]
     ,mySource.[r3y_client_pe_sp]
     ,mySource.[r3y_client_tkt_price]
     ,mySource.[r1y_client_event_cnt]
     ,mySource.[r1y_client_tkt_cnt]
     ,mySource.[r1y_client_sp]
     ,mySource.[r1y_client_pe_tkt]
     ,mySource.[r1y_client_pe_sp]
     ,mySource.[r1y_client_tkt_price]
     ,mySource.[dist_to_client_ven]
     ,mySource.[dist_to_client_event]
     ,mySource.[sale_dt_max]
     ,mySource.[event_dt_max]
     ,mySource.[e3_tran_cnt]
     ,mySource.[e3_event_cnt]
     ,mySource.[e3_tkt_cnt]
     ,mySource.[e3_tran_amt]
     ,mySource.[py_tran_avg]
     ,mySource.[py_event_avg]
     ,mySource.[py_tkt_avg]
     ,mySource.[py_tran_amt]
     ,mySource.[pe_tran_avg]
     ,mySource.[pe_tkt_avg]
     ,mySource.[pe_tran_amt]
     ,mySource.[tkt_price_avg]
     ,mySource.[tkt_price_min]
     ,mySource.[tkt_price_max]
     ,mySource.[tkt_qty_purch_01_02_cnt]
     ,mySource.[tkt_qty_purch_03_04_cnt]
     ,mySource.[tkt_qty_purch_05_08_cnt]
     ,mySource.[tkt_qty_purch_09_plus_cnt]
     ,mySource.[tkt_price_000_025_cnt]
     ,mySource.[tkt_price_026_050_cnt]
     ,mySource.[tkt_price_051_100_cnt]
     ,mySource.[tkt_price_101_200_cnt]
     ,mySource.[tkt_price_201_plus_cnt]
     ,mySource.[tkt_type_low_cnt]
     ,mySource.[tkt_type_mid_cnt]
     ,mySource.[tkt_type_high_cnt]
     ,mySource.[tkt_type_super_cnt]
     ,mySource.[tkt_type_vip_cnt]
     ,mySource.[dist_to_ven]
     ,mySource.[dist_to_ven_local]
     ,mySource.[dist_000_010_ind]
     ,mySource.[dist_011_025_ind]
     ,mySource.[dist_026_050_ind]
     ,mySource.[dist_051_100_ind]
     ,mySource.[dist_101_200_ind]
     ,mySource.[dist_201_plus_ind]
     ,mySource.[prkg_ind]
     ,mySource.[pmt_visa_ind]
     ,mySource.[pmt_mastercard_ind]
     ,mySource.[pmt_amex_ind]
     ,mySource.[pmt_discover_ind]
     ,mySource.[pmt_oth_ind]
     ,mySource.[e3_chnl_inet_ind]
     ,mySource.[e3_chnl_phn_ind]
     ,mySource.[e3_dlvry_willcall_ind]
     ,mySource.[e3_dlvry_ups_ind]
     ,mySource.[e3_dlvry_ticketfast_ind]
     ,mySource.[e3_dlvry_mail_ind]
     ,mySource.[e3_dlvry_paperless_ind]
     ,mySource.[e3_dlvry_oth_ind]
     ,mySource.[purch_presale_ind]
     ,mySource.[purch_onsale_ind]
     ,mySource.[purch_first_wk_ind]
     ,mySource.[purch_inbetween_ind]
     ,mySource.[purch_final_wk_ind]
     ,mySource.[m_concerts_presale_ind]
     ,mySource.[m_concerts_first_dy_ind]
     ,mySource.[m_concerts_first_wk_ind]
     ,mySource.[m_concerts_inbetween_ind]
     ,mySource.[m_concerts_final_wk_ind]
     ,mySource.[m_arts_presale_ind]
     ,mySource.[m_arts_first_dy_ind]
     ,mySource.[m_arts_first_wk_ind]
     ,mySource.[m_arts_inbetween_ind]
     ,mySource.[m_arts_final_wk_ind]
     ,mySource.[m_fmly_presale_ind]
     ,mySource.[m_fmly_first_dy_ind]
     ,mySource.[m_fmly_first_wk_ind]
     ,mySource.[m_fmly_inbetween_ind]
     ,mySource.[m_fmly_final_wk_ind]
     ,mySource.[m_sports_presale_ind]
     ,mySource.[m_sports_first_dy_ind]
     ,mySource.[m_sports_first_wk_ind]
     ,mySource.[m_sports_inbetween_ind]
     ,mySource.[m_sports_final_wk_ind]
     ,mySource.[e3_m_concerts_cnt]
     ,mySource.[e3_m_arts_cnt]
     ,mySource.[e3_m_fmly_cnt]
     ,mySource.[e3_m_sports_cnt]
     ,mySource.[e3_m_concerts_sp]
     ,mySource.[e3_m_arts_sp]
     ,mySource.[e3_m_fmly_sp]
     ,mySource.[e3_m_sports_sp]
     ,mySource.[py_m_concerts_cnt]
     ,mySource.[py_m_arts_cnt]
     ,mySource.[py_m_fmly_cnt]
     ,mySource.[py_m_sports_cnt]
     ,mySource.[py_m_concerts_sp]
     ,mySource.[py_m_arts_sp]
     ,mySource.[py_m_fmly_sp]
     ,mySource.[py_m_sports_sp]
     ,mySource.[pe_m_concerts_tkt]
     ,mySource.[pe_m_arts_tkt]
     ,mySource.[pe_m_fmly_tkt]
     ,mySource.[pe_m_sports_tkt]
     ,mySource.[pe_m_concerts_sp]
     ,mySource.[pe_m_arts_sp]
     ,mySource.[pe_m_family_sp]
     ,mySource.[pe_m_sports_sp]
     ,mySource.[pe_m_concerts_spi]
     ,mySource.[pe_m_arts_spi]
     ,mySource.[pe_m_fmly_spi]
     ,mySource.[pe_m_sports_spi]
     ,mySource.[mon_between_purch]
     ,mySource.[mon_between_event]
     ,mySource.[mon_since_last_event]
     ,mySource.[mon_since_last_purch]
     ,mySource.[r5_cd]
     ,mySource.[f5_cd]
     ,mySource.[m5_tkt_price_cd]
     ,mySource.[m5_tkt_type_cd]
     ,mySource.[brkr_ind]
     ,mySource.[grp_buyer_ind]
     ,mySource.[multi_tkt_16_plus_ind]
     ,mySource.[grade_fm_cd]
     ,mySource.[grade_rfm_cd]
     ,mySource.[score_fm5]
     ,mySource.[score_rfm5]
     ,mySource.[e3_ms_a_brwymus_ind]
     ,mySource.[e3_ms_a_comedy_ind]
     ,mySource.[e3_ms_a_clasopera_ind]
     ,mySource.[e3_ms_a_oth_ind]
     ,mySource.[e3_ms_c_adultcont_ind]
     ,mySource.[e3_ms_c_altrock_ind]
     ,mySource.[e3_ms_c_ctry_ind]
     ,mySource.[e3_ms_c_dancemus_ind]
     ,mySource.[e3_ms_c_hardrock_ind]
     ,mySource.[e3_ms_c_jazz_ind]
     ,mySource.[e3_ms_c_latin_ind]
     ,mySource.[e3_ms_c_hiphop_ind]
     ,mySource.[e3_ms_c_rbsoul_ind]
     ,mySource.[e3_ms_c_rockpop_ind]
     ,mySource.[e3_ms_c_oth_ind]
     ,mySource.[e3_ms_s_boxmmawres_ind]
     ,mySource.[e3_ms_s_motor_ind]
     ,mySource.[e3_ms_s_rodeo_ind]
     ,mySource.[e3_ms_s_oth_ind]
     ,mySource.[e3_ms_f_fmly_ind]
     ,mySource.[propn_f_fmly]
     ,mySource.[propn_a_brwymus]
     ,mySource.[propn_a_arts_oth]
     ,mySource.[propn_c_altrock]
     ,mySource.[propn_c_comedy]
     ,mySource.[propn_c_ctry]
     ,mySource.[propn_c_hardrock]
     ,mySource.[propn_c_jazz]
     ,mySource.[propn_c_latin]
     ,mySource.[propn_c_rbsoul]
     ,mySource.[propn_c_rap]
     ,mySource.[propn_c_rockpop]
     ,mySource.[propn_c_oth]
     ,mySource.[propn_s_baseb]
     ,mySource.[propn_s_bsktb]
     ,mySource.[propn_s_footb]
     ,mySource.[propn_s_hockey]
     ,mySource.[propn_s_motor]
     ,mySource.[propn_s_sports_oth]
     ,mySource.[r3y_event_cnt]
     ,mySource.[r3y_tkt_cnt]
     ,mySource.[r3y_tran_amt]
     ,mySource.[r3y_pe_tkt]
     ,mySource.[r3y_pe_tran_amt]
     ,mySource.[r3y_tkt_price_avg]
     ,mySource.[r3y_tkt_price_000_025_ind]
     ,mySource.[r3y_tkt_price_026_050_ind]
     ,mySource.[r3y_tkt_price_051_100_ind]
     ,mySource.[r3y_tkt_price_101_200_ind]
     ,mySource.[r3y_tkt_price_201_plus_ind]
     ,mySource.[r3y_tkt_type_low_ind]
     ,mySource.[r3y_tkt_type_mid_ind]
     ,mySource.[r3y_tkt_type_high_ind]
     ,mySource.[r3y_tkt_type_super_ind]
     ,mySource.[r3y_tkt_type_vip_ind]
     ,mySource.[r3y_dist_000_010_ind]
     ,mySource.[r3y_dist_011_025_ind]
     ,mySource.[r3y_dist_026_050_ind]
     ,mySource.[r3y_dist_051_100_ind]
     ,mySource.[r3y_dist_101_200_ind]
     ,mySource.[r3y_dist_201_plus_ind]
     ,mySource.[r3y_prkg_ind]
     ,mySource.[r3y_ms_a_brwymus_ind]
     ,mySource.[r3y_ms_a_comedy_ind]
     ,mySource.[r3y_ms_a_clasopera_ind]
     ,mySource.[r3y_ms_a_oth_ind]
     ,mySource.[r3y_ms_c_adultcont_ind]
     ,mySource.[r3y_ms_c_altrock_ind]
     ,mySource.[r3y_ms_c_ctry_ind]
     ,mySource.[r3y_ms_c_dancemus_ind]
     ,mySource.[r3y_ms_c_hardrock_ind]
     ,mySource.[r3y_ms_c_jazz_ind]
     ,mySource.[r3y_ms_c_latin_ind]
     ,mySource.[r3y_ms_c_hiphop_ind]
     ,mySource.[r3y_ms_c_rbsoul_ind]
     ,mySource.[r3y_ms_c_rockpop_ind]
     ,mySource.[r3y_ms_c_oth_ind]
     ,mySource.[r3y_ms_s_boxmmawres_ind]
     ,mySource.[r3y_ms_s_motor_ind]
     ,mySource.[r3y_ms_s_rodeo_ind]
     ,mySource.[r3y_ms_s_oth_ind]
     ,mySource.[r3y_ms_f_fmly_ind]
     ,mySource.[race_cd]
     ,mySource.[net_worth_gold_cd]
     ,mySource.[est_hh_inc_higher_ranges_cd]
     ,mySource.[est_hh_inc_narrow_ranges_cd]
     ,mySource.[est_hh_inc_cd_100pct_inc_cd]
     ,mySource.[est_hh_inc_cd_100pct_prec_cd]
     ,mySource.[first_indv_first_nm]
     ,mySource.[first_indv_md_nm]
     ,mySource.[second_indv_first_nm]
     ,mySource.[second_indv_md_nm]
     ,mySource.[bo_out_sale_dt_min]
     ,mySource.[bo_out_sale_dt_max]
     ,mySource.[bo_out_event_dt_min]
     ,mySource.[bo_out_event_dt_max]
     ,mySource.[bo_out_tot_tran_amt]
     ,mySource.[bo_out_pe_tran_amt]
     ,mySource.[bo_out_tot_tran_cnt]
     ,mySource.[bo_out_tot_event_cnt]
     ,mySource.[bo_out_purch_dy_of_event_cnt]
     ,mySource.[bo_out_purch_1_wk_before_cnt]
     ,mySource.[bo_out_purch_2_wk_before_cnt]
     ,mySource.[bo_out_purch_3_wk_before_cnt]
     ,mySource.[bo_out_purch_4_wk_before_cnt]
     ,mySource.[bo_out_purch_5_wk_before_cnt]
     ,mySource.[bo_out_client_sale_dt_min]
     ,mySource.[bo_out_client_sale_dt_max]
     ,mySource.[bo_out_client_event_dt_min]
     ,mySource.[bo_out_client_event_dt_max]
     ,mySource.[bo_out_client_tot_tran_amt]
     ,mySource.[bo_out_client_pe_tran_amt]
     ,mySource.[bo_out_client_tot_event_cnt]
     ,mySource.[bo_out_ven_sale_dt_min]
     ,mySource.[bo_out_ven_sale_dt_max]
     ,mySource.[bo_out_ven_event_dt_min]
     ,mySource.[bo_out_ven_event_dt_max]
     ,mySource.[bo_out_ven_tot_tran_amt]
     ,mySource.[bo_out_ven_pe_tran_amt]
     ,mySource.[bo_out_ven_tot_event_cnt]
     ,mySource.[msa_nm]
     )
;



DECLARE @MergeInsertRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM ods.LiveAnalytics_Customer WHERE ETL_CreatedDate >= @RunTime AND ETL_UpdatedDate = ETL_CreatedDate),'0');	
DECLARE @MergeUpdateRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM ods.LiveAnalytics_Customer WHERE ETL_UpdatedDate >= @RunTime AND ETL_UpdatedDate > ETL_CreatedDate),'0');	


END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage nvarchar(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)

END CATCH


END

GO
