CREATE TABLE [apietl].[Appetize_Items_0]
(
[ETL__Appetize_Items_id] [uniqueidentifier] NOT NULL,
[ETL__session_id] [uniqueidentifier] NOT NULL,
[ETL__insert_datetime] [datetime] NOT NULL CONSTRAINT [DF__Appetize___ETL____74F0ADE3] DEFAULT (getutcdate()),
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentItemId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unique_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subvendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignment_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_group_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mixer_icon_url] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show_desc] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_alcohol] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[restrict_single_modifier] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[track_inventory] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventory_amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mark_as_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show_in_browse] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_clickable] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[require_additional] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original_bundle_cost] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_price_override] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[upsell_item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[barcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sku] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[active_start] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[active_end] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wizard] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isOpenPrice] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isWeightItem] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[weightUnits] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_update] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sales_account_code_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost_account_code_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isSuiteItem] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isPackageItem] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxStartDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxEndDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calories] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[caloriesLabel] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_group_2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_group_3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tareWeight] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_text_color] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_bg_color] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[displayName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[receiptTrailerMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[taxGroupId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oldTaxGroupId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [apietl].[Appetize_Items_0] ADD CONSTRAINT [PK__Appetize__92DDD59307726232] PRIMARY KEY CLUSTERED  ([ETL__Appetize_Items_id])
GO
