CREATE TABLE [AUDIT].[ArenaBounceBackFulls]
(
[recordid] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q20_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q23_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q22_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q21] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q14] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_5] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_7] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_8] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_9] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2_10] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4SPECIFIED_6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q5] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q5SPECIFIED_6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q7] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q8SPECIFIED_5] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_5] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_7] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q9_8] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q10] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q11_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q13] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q15] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_5] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_7] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q16_8] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q17] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_5] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_6] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q18_7] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q19] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q24] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q26_1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q26_2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q26_3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q26_4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Campaign Name] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Campaign Type] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Started] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Completed] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Branched Out] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Over Quota] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Modified] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Campaign Status] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Culture] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Page] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Response Source] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Type] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Task ID] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occurrence] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Referring URL] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Browser's User Agent] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Respondent's IP Address] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Respondent's Hostname] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParticipantURL] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Browser Family] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Browser Version] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Operating System Family] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Operating System Name] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Device Type] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State Province] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP Postal Code] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Longitude] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
