CREATE TABLE [dbo].[Appetize_Items_Old]
(
[item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentItemId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unique_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subvendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignment_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_group_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show_desc] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cost] [numeric] (13, 4) NULL,
[type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_alcohol] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[restrict_single_modifier] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[track_inventory] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inventory_amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mark_as_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show_in_browse] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_clickable] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[require_additional] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[original_bundle_cost] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_price_override] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[upsell_item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[barcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sku] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[active_start] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[active_end] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wizard] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isOpenPrice] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isWeightItem] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[weightUnits] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_update] [datetime2] NULL,
[tax_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secondary_item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
