CREATE TABLE [dbo].[Appetize_Vendors]
(
[id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[username] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printer_ip] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[staff_members] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[order_capacity] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fast_pass_lane] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status_description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drink_limit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_enabled] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[wait_m] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[welcome_text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickup_location] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[additional_info] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_screen] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[login_required] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tip_enabled] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fee] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fee_in_percent] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[convince_fee] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fee_text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[image_url] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat_confirmation] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[food_count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drink_count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mixer_count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mixer_built_count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[merch_count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bundle_count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[collected_tax_rate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_on_total] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_on_tip] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_on_fee] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax_charge_after_discount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quick_order_view] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[quick_order_image] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_drink_limit_per_event] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
