CREATE TABLE [dbo].[Audit_Appetize_Orders]
(
[ACTION] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_DATE] [datetime2] NULL,
[inserted_order_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_mobile] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_level] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_section] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_row] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_seat] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_user_seat_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_order_source] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_total] [decimal] (13, 4) NULL,
[inserted_original_subtotal] [decimal] (13, 4) NULL,
[inserted_tip] [decimal] (13, 4) NULL,
[inserted_fee] [decimal] (13, 4) NULL,
[inserted_tax] [decimal] (13, 4) NULL,
[inserted_status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_vendor_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_order_mode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_payment_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_timezone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_order_date] [datetime2] NULL,
[inserted_date_modified] [datetime2] NULL,
[inserted_date_completed] [datetime2] NULL,
[inserted_offline_mode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_device_token] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_card_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_order_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_mobile] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_level] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_section] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_row] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_seat] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_user_seat_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_order_source] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_total] [decimal] (13, 4) NULL,
[deleted_original_subtotal] [decimal] (13, 4) NULL,
[deleted_tip] [decimal] (13, 4) NULL,
[deleted_fee] [decimal] (13, 4) NULL,
[deleted_tax] [decimal] (13, 4) NULL,
[deleted_status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_vendor_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_order_mode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_payment_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_timezone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_order_date] [datetime2] NULL,
[deleted_date_modified] [datetime2] NULL,
[deleted_date_completed] [datetime2] NULL,
[deleted_offline_mode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_device_token] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_card_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
