CREATE TABLE [dbo].[Audit_Appetize_Items]
(
[ACTION] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_DATE] [datetime2] NULL,
[inserted_item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_parentItemId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_unique_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_subvendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_assignment_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_category_group_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_category_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_show_desc] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_cost] [decimal] (13, 4) NULL,
[inserted_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_is_alcohol] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_restrict_single_modifier] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_track_inventory] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_inventory_amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_mark_as_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted__sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_show_in_browse] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_is_clickable] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_require_additional] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_original_bundle_cost] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_add_price_override] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_upsell_item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_barcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_sku] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_active_start] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_active_end] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_wizard] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_isOpenPrice] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_isWeightItem] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_weightUnits] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_last_update] [datetime2] NULL,
[inserted_tax_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inserted_secondary_item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_parentItemId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_unique_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_vendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_subvendor_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_assignment_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_category_group_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_category_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_show_desc] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_cost] [decimal] (13, 4) NULL,
[deleted_type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_is_alcohol] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_restrict_single_modifier] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_track_inventory] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_inventory_amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_mark_as_sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted__sold_out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_show_in_browse] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_is_clickable] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_require_additional] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_original_bundle_cost] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_add_price_override] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_upsell_item_id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_barcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_sku] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_active_start] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_active_end] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_wizard] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_isOpenPrice] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_isWeightItem] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_weightUnits] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_last_update] [datetime2] NULL,
[deleted_tax_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deleted_secondary_item_group] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
