CREATE TABLE [ods].[Host_Trans]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREFIX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLEINITIAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUFFIX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPEXT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DAYPHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVENINGPHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_EVENT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERACTION_SOURCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALEDATE] [date] NULL,
[TICKETS] [int] NULL,
[TRANSACTION_AMOUNT] [decimal] (18, 6) NULL,
[ACCOUNT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VOIDED_FLAG] [bit] NULL,
[VOIDED_DATE] [date] NULL,
[PAYMENT_SUBMETHOD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMEFROM_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEATINFO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUALIFIERS] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACILITY_FEE] [decimal] (18, 6) NULL,
[SERVICE_CHARGE] [decimal] (18, 6) NULL,
[TRANSACTION_NUM] [int] NULL,
[OPTION_DOLLARS] [decimal] (18, 6) NULL,
[VAXNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOBILEPHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPCODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPLEVEL] [int] NULL,
[EXTRA1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TICKETS_TRANSFERRED] [bit] NULL,
[TICKETS_RECEIVED] [bit] NULL,
[TICKETS_SURRENDERED] [bit] NULL,
[EVENT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_MAJORCATNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_MINORCATNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENUENUM] [int] NULL,
[VENUENAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVENTDATE] [datetime] NULL,
[ONSALEDATE] [datetime] NULL,
[PRESALEONDATE] [datetime] NULL,
[PRESALEOFFDATE] [datetime] NULL,
[OUTLETDATE] [datetime] NULL,
[PHONEDATE] [datetime] NULL,
[CANCELLED] [bit] NULL,
[VENUE_CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENUE_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENUE_ZIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TICKET_TEXT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYACT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SECONDARYACT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERFNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPT_IN_FLAG] [bit] NULL,
[Calc_HostAccountId] [int] NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI__ods_Host_Trans] ON [ods].[Host_Trans]
GO
