CREATE TABLE [ods].[Host_Trans_ActiveSales]
(
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_UpdatedDate] [datetime] NOT NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SSID_AccountKey] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCOUNT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVENT_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALEDATE] [datetime] NULL,
[SEATINFO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TICKETS] [int] NULL,
[TRANSACTION_NUM] [int] NULL,
[EVENTDATE] [datetime] NULL,
[PERFNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYACT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SECONDARYACT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_EVENT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_MAJORCATNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_MINORCATNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VAXNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENUENAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENUENUM] [int] NULL,
[CAMEFROM_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTRA2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERACTION_SOURCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPT_IN_FLAG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYMENT_SUBMETHOD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUALIFIERS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatRanking] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SectionName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatStart] [int] NULL,
[SeatEnd] [int] NULL,
[PriceType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSACTION_AMOUNT] [decimal] (18, 6) NULL,
[Calc_HostAccountId] [int] NULL,
[ETL__ID] [int] NULL,
[ETL__SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
