CREATE TABLE [stg].[Host_Audit]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[System] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HexVaxEVID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EvCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MajorCategory] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinorCategory] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondActName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VenueName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EPDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EPTime] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sdate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevelName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QualifierString] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuditEntry] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeriesMaster] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DailyTickets] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalTickets] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldFaceValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceCharge] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityFee] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceTax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VATTax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdultPrice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremiumAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QualifierMaskName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
