CREATE TABLE [stg].[formstack_historical_files_Deduped]
(
[Time] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parent_Guardian_Name_First] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parent_Guardian_NameLast] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Parent_Guardian_Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[How many children would you like to sign up?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child Name (First)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child Name (Last)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child Birthday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #2 Name (First)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #2 Name (Last)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #2 Birthday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender #2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #3 Name (First)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #3 Name (Last)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #3 Birthday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender #3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #4 Name (First)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #4 Name (Last)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child #4 Birthday] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender #4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[How many kits would you like to donate?] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Browser] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IP Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UniqueID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payment Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingZip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rnk] [bigint] NULL
)
GO
