CREATE TABLE [zfrick].[mv_FactTicketSeat]
(
[SaleDate] [date] NULL,
[SaleTime] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SaleDateTime] [datetime] NULL,
[AccountId] [int] NULL,
[ArenaCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArenaName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonHeaderYear] [int] NULL,
[SeasonHeaderIsActive] [bit] NULL,
[SeasonName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonYear] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonIsActive] [bit] NULL,
[EventHeaderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHeaderDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHeaderDate] [date] NULL,
[EventHeaderTime] [time] NULL,
[EventHeaderDateTime] [datetime] NULL,
[EventHeaderOpenTime] [datetime] NULL,
[EventHeaderFinishTime] [datetime] NULL,
[EventSeasonNumber] [int] NULL,
[EventHeaderHomeNumber] [int] NULL,
[EventHeaderGameNumber] [int] NULL,
[EventHierarchyL1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventHierarchyL5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventDate] [date] NULL,
[EventTime] [time] NULL,
[EventDateTime] [datetime] NULL,
[EventClass] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MajorCategoryTM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinorCategoryTM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemPlanOrEvent] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanDesc] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanClass] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanFse] [decimal] (3, 2) NULL,
[PlanType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanEventCnt] [int] NULL,
[PriceCode] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC2] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pc3] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC4] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceCodeDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceCodeGroup] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SectionName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Seat] [int] NULL,
[SeatLocationMapping] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketClassCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketTypeName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanTypeCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanTypeName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatTypeCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatTypeName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistStatus] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesCodeName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManifestedPriceCode] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManifestedClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManifestedSeatValue] [numeric] (18, 6) NOT NULL,
[PostedPriceCode] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostedClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostedSeatValue] [numeric] (18, 6) NULL,
[HeldPriceCode] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeldClassName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeldSeatValue] [decimal] (18, 6) NULL,
[IsSaleable] [bit] NOT NULL,
[IsAvailable] [bit] NOT NULL,
[IsHeld] [bit] NOT NULL,
[IsReserved] [bit] NOT NULL,
[IsSold] [bit] NOT NULL,
[IsHost] [bit] NULL,
[IsComp] [bit] NOT NULL,
[CompCode] [int] NULL,
[CompName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPremium] [bit] NULL,
[IsSingleEvent] [bit] NULL,
[IsPlan] [bit] NULL,
[IsPartial] [bit] NULL,
[IsGroup] [bit] NULL,
[IsRenewal] [bit] NULL,
[IsBroker] [bit] NULL,
[TotalRevenue] [decimal] (18, 6) NOT NULL,
[PcTicketValue] [decimal] (18, 6) NOT NULL,
[Surcharge] [decimal] (18, 6) NOT NULL,
[PcTicket] [decimal] (18, 6) NOT NULL,
[PcTax] [decimal] (18, 6) NOT NULL,
[PcLicenseFee] [decimal] (18, 6) NOT NULL,
[PcOther1] [decimal] (18, 6) NOT NULL,
[PcOther2] [decimal] (18, 6) NOT NULL,
[IsAttended] [bit] NOT NULL,
[ScanDateTime] [datetime] NULL,
[ScanGate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtySeatFSE] [decimal] (38, 20) NULL,
[PaidAmount] [decimal] (38, 20) NULL,
[OwedAmount] [decimal] (38, 20) NULL,
[OrderNum] [bigint] NULL,
[OrderLineItem] [int] NULL,
[RetailTicketType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailQualifiers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsResold] [int] NULL,
[ResoldDateTime] [datetime] NULL,
[ResoldPurchasePrice] [decimal] (18, 6) NULL,
[ResoldFees] [decimal] (18, 6) NULL,
[ResoldTotalAmount] [decimal] (18, 6) NULL,
[Org] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FactInventoryId] [int] NOT NULL,
[FactTicketSalesId] [bigint] NULL,
[DimSeasonId] [int] NOT NULL,
[DimEventId] [int] NOT NULL,
[DimSeatId] [int] NOT NULL,
[SoldDimPriceCodeId] [int] NULL,
[SoldDimItemId] [int] NULL,
[SoldDimPlanId] [int] NULL,
[SoldDimCustomerId] [bigint] NULL,
[SoldDimDateId] [int] NULL,
[SoldDimTimeId] [int] NULL,
[SoldDimClassTMId] [int] NULL,
[SoldDimSalesCodeId] [int] NULL,
[SoldDimPromoId] [int] NULL,
[DimPlanTypeId] [int] NULL,
[DimTicketTypeId] [int] NULL,
[DimSeatTypeId] [int] NULL,
[ResoldDimCustomerId] [int] NULL,
[DimSeasonHeaderId] [int] NOT NULL,
[PrevSeasonHeaderId] [int] NULL,
[DimEventHeaderId] [int] NOT NULL,
[PrevSeasonId] [int] NULL,
[SSID_event_id] [int] NULL,
[SSID_section_id] [int] NULL,
[SSID_row_id] [int] NULL,
[SSID_seat] [int] NULL,
[SalesSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupSalesName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchticsAddUser] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustomerIdSalesRep] [bigint] NULL,
[DimCustomerId_TransSalesRep] [bigint] NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CSI_mv_FactTicketSeat] ON [zfrick].[mv_FactTicketSeat]
GO
